---
sidebar: sidebar 
permalink: nkfsosm_performance.html 
keywords: netapp, keystone, performance, service levels 
summary: Livello di servizio delle performance Keystone 
---
= Livelli di servizio
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Keystone offre capacità di storage dei dati a livelli di servizio (livelli di servizio) o piani tariffari predefiniti per le performance, su base di abbonamento. Ogni volume gestito dai servizi Keystone è associato a un livello di servizio.

Ciascun livello di servizio è definito dalla densità i/o, ovvero IOPS/TIB/volume. Si tratta del rapporto tra performance (operazioni di input/output al secondo [IOPS]) e capacità di storage allocata (TIB), ovvero IOPS/TIB con latenza media per volume.

La densità i/o di un volume viene calcolata a intervalli orari per indicare la densità i/o di picco. I report di densità i/o per i volumi vengono generati mensilmente.

È possibile selezionare i livelli di servizio in base all'ambiente di storage e alle esigenze di storage e consumo. I livelli di servizio di base sono disponibili per impostazione predefinita. Se hai scelto servizi specifici, sono disponibili anche altri livelli di servizio. Ad esempio, per il servizio di protezione dei dati, il livello di servizio _Data-Protect <base-service-level>_ viene assegnato all'abbonamento.

I livelli di servizio di base per i tipi di storage a file, blocchi e oggetti sono elencati qui.



== Livelli di servizio per lo storage dei file

*Protocolli supportati*: NFS, CIFS, iSCSI e FC

|===


| *Livello di servizio* | *Estrema* | *Premium* | *Standard* | *Valore* 


| *Tipo di carico di lavoro* | Analytics, database | VDI, applicazioni di virtualizzazione, sviluppo software | Condivisioni di file, server web | Backup 


| *Massimo IOPS/TIB logico allocato per volume* | 12,288 | 4,096 | 512 | N/A. 


| *IOPS di destinazione/TIB logico allocati per volume* | 6,144 | 2,048 | 128 | N/A. 


| *Numero massimo di Mbps/TIB logici allocati per volume* | 384 | 128 | 16 | N/A. 


| *Latenza media* | <1 ms. | <2 ms. | <17 ms. | N/A. 


| *Dimensione del blocco* 4+| 32.000 
|===


=== Ulteriori informazioni sui livelli di servizio per lo storage dei file

Le metriche del livello di servizio di base dipendono dalle seguenti condizioni:

* I livelli di servizio per lo storage a blocchi e file supportano ONTAP 9.7 e versioni successive.
* I valori di IOPS/TIB/volume, Mbps/TIB/volume e latenza per i livelli di servizio si basano sulla quantità di dati logici memorizzati nel volume, sulla dimensione del blocco di 32 KB e su una combinazione casuale di operazioni io in lettura al 70% e in scrittura al 30%.
* IOPS/TIB/volume effettivo e Mbps/TIB/volume possono variare in base alle dimensioni effettive o presunte del blocco, alla concorrenza dei carichi di lavoro del sistema o alle operazioni input-output.
* La latenza non include quanto segue:
+
** latenza dell'applicazione o dell'host
** latenza di rete del cliente da o verso le porte del controller
** Overhead associati al trasferimento dei dati nell'archivio di oggetti in caso di FabricPool
** Latenza applicata automaticamente dalla QoS per mantenere i/o entro i massimi livelli di servizio


* I valori di latenza non sono applicabili alle operazioni di scrittura MetroCluster. Queste operazioni di scrittura dipendono dalla distanza dei sistemi remoti.
* Se uno o più volumi su un sistema storage non hanno una policy AQoS assegnata, questi volumi vengono considerati come volumi non conformi e non sono applicabili livelli di servizio di destinazione per tali sistemi.
* _Gli IOPS previsti_ sono destinati a FabricPool solo se la policy di tiering è impostata su "nessuno" e non ci sono blocchi nel cloud. _Gli IOPS previsti_ sono destinati a volumi che non sono in una relazione sincrona di SnapMirror.
* Le operazioni di i/o dei workload devono essere bilanciate in tutti i controller implementati, come stabilito dall'ordine Keystone.




== Livelli di servizio per lo storage a blocchi

*Protocolli supportati*: FC e iSCSI

|===


| *Livello di servizio* | *Estrema* | *Premium* | *Standard* 


| *Tipo di carico di lavoro* | HPC | Videosorveglianza | Backup 


| *IOPS/TIB di destinazione* 3+| N/A. 


| *IOPS/TIB max* | 5,500 | 4,000 | N/A. 


| *Throughput massimo Mbps (32 KB/IOP)* | 43 | 31 | N/A. 


| *Latenza media* | <0.5 ms. | <0.5 ms. | N/A. 


| *Dimensione del blocco* 3+| 32.000 
|===


== Livelli di servizio per lo storage a oggetti

*Protocollo supportato*: S3

|===


| *Livello di servizio* | Oggetto 


| *Tipo di carico di lavoro* | Repository di contenuti multimediali, archiviazione 


| *IOPS/TIB di destinazione* | N/A. 


| *IOPS/TIB max* | N/A. 


| *Throughput massimo Mbps (32 KB/IOP)* | N/A. 


| *Latenza media* | N/A. 
|===