---
sidebar: sidebar 
permalink: nkfsfaq_netapp_service_engine_self-service_access_portal.html 
keywords: netapp, keystone, service, engine, self-service, acess, portal, 
summary: NetApp Service Engine/Self-Service Access Portal 
---
= NetApp Service Engine/portale di accesso self-service
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Le seguenti domande frequenti si applicano a NetApp Service Engine.

*Cos'è NetApp Service Engine?*

Il motore di servizi NetApp è un portale self-service disponibile nel modello gestito da NetApp per l'accesso e il provisioning dello storage in base al servizio NetApp Keystone. Il tool fornisce inoltre report sui livelli di consumo rispetto all'abbonamento e avvia eventuali richieste di servizio o modifiche all'abbonamento.

*NetApp Service Engine richiesto nel modello gestito dal cliente?*

In un modello gestito dal cliente, è necessario NetApp Service Engine. Fornisce report di base sui dettagli di consumo ed è necessario per raccogliere e segnalare le informazioni di fatturazione.

*Dove è installato NetApp Service Engine?*

In un modello gestito da NetApp, NetApp Service Engine viene installato localmente sulle risorse di calcolo fornite da NetApp. In un modello gestito dal cliente, NetApp Service Engine viene installato sulle risorse di calcolo fornite dal cliente.

*Chi può accedere a NetApp Service Engine?*

Gli utenti possono essere autenticati con NetApp SSO o utenti locali configurati in NetApp Service Engine.

*Come viene controllato l'accesso?*

NetApp Service Engine fornisce RBAC (role-based access control) e ciascun utente può essere associato a un ruolo, che definisce le azioni che può eseguire. L'assegnazione RBAC viene eseguita dal cliente utilizzando NetApp Service Engine.

*Quali controlli di accesso sono disponibili?*

Sono disponibili i seguenti controlli di accesso:

* *Partner Admin* Amministratore del partner che ha i diritti di creare e gestire tenant, gestire sottoscrizioni per tenant, visualizzare report sull'utilizzo e gestire aspetti tecnici dello storage.
* *Customer/tenant Admin.* persona amministrativa del cliente che ha il diritto di richiedere modifiche all'abbonamento, creare nuovi utenti e subtenant, nonché creare e visualizzare condivisioni di file, dischi e bucket.
* *Amministratore NetApp (lettura).* un amministratore NetApp, che ha accesso a tutti i componenti del portale Web e può visualizzare tutti i dettagli, come tutti i NetApp Keystone, gli abbonamenti ai partner e ai tenant e lo storage. Tuttavia, questo utente non dispone di autorizzazioni per creare, modificare o eliminare.
* *Amministratore NetApp* questo utente dispone di accesso completo e autorizzazioni per eseguire tutte le funzioni del portale Web del motore di servizio NetApp per la gestione di NetApp Keystone e tutte le attività per l'amministrazione di partner e tenant.


*Dove è possibile visualizzare la fatturazione rispetto all'utilizzo?*

Puoi visualizzare gli addebiti mensili aggregati per gli abbonamenti degli ultimi tre mesi nel widget *addebiti mensili* della dashboard. Per visualizzare informazioni dettagliate sulla fatturazione, fare clic nel widget o accedere a *AMMINISTRAZIONE* > *fatturazione*.
