---
sidebar: sidebar 
permalink: nkfsosm_netapp_global_services_and_support_center_@gssc@.html 
keywords: netapp, keystone, global, services, support, center, gssc, 
summary: 'NetApp Global Services and Support Center (GSSC)' 
---
= Operazioni di Keystone Services
:allow-uri-read: 


[role="lead"]
I servizi Keystone di NetApp Keystone vengono eseguiti sfruttando il centro servizi e supporto globale NetApp (GSSC), il gestore di successo NetApp Keystone e il gestore di erogazione dei servizi NetApp Keystone.



== NetApp Global Services and Support Center (GSSC)

NetApp fornisce servizi operativi in remoto ai clienti NetApp Keystone. Questi servizi comprendono una vasta gamma di discipline operative per le attività di gestione dello storage, tra cui gestione di risorse e configurazione, gestione di capacità e performance, gestione delle modifiche, gestione di eventi, incidenti e problemi, evasione delle richieste di servizio e reporting. NetApp dimostrerà lo stato di controllo e le prove a supporto disponibili secondo necessità.



== Informazioni aggiuntive e contatto per il supporto

Il team dei servizi e supporto globali NetApp (GSSC) supporta principalmente i servizi ai clienti NetApp Keystone.

Inviare un ticket direttamente dal portale NetApp Service Engine (*Support > Service Requests*) con i dettagli appropriati del problema per ricevere assistenza.

Puoi anche utilizzare le seguenti informazioni per contattare il team di supporto.

* Contatti Global Service:https://www.netapp.com/us/contact-us/support.aspx[]
* Se si dispone di un caso/ticket aperto che deve essere sottoposto a escalation, inviare un'e-mail a uno dei seguenti indirizzi: Keystone.services@netapp.com Keystone.escalations@netapp.com
* NetApp utilizza OpsRamp, una soluzione di gateway remoto basata sul cloud per monitorare e connettersi in modo proattivo all'ambiente NetApp Keystone per la risoluzione dei problemi. Per informazioni su OpsRamp, vedere https://www.opsramp.com/#[].



NOTE: In un modello gestito dal partner, le richieste di servizio del tenant e del subtenant vengono assegnate al service desk del partner. Il tool di supporto del partner potrebbe essere integrato con le applicazioni OpsRamp e GSSC. Solo i problemi L3 vengono inoltrati a NetApp tramite GSSC.

Per ulteriori informazioni sulle informazioni descritte in questo documento, consultare i seguenti documenti e/o siti Web:

* NetApp Keystonehttps://www.netapp.com/us/solutions/keystone/index.aspx["https://www.netapp.com/us/solutions/keystone/index.aspx"^]
* Documentazione sui prodotti NetApphttps://docs.netapp.com["https://docs.netapp.com"^]

