---
settings:
  name: Keystone
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Servizi NetApp Keystone
    url: "/index.html"
    entries:
    - title: Termini e descrizione del servizio
      url: "/nkfsosm_service_terms_and_description_overview.html"
      entries:
      - title: Definizioni della capacità del servizio
        url: "/nkfsosm_keystone_service_capacity_definitions.html"
      - title: Livelli di servizio in Keystone
        url: "/nkfsosm_performance.html"
      - title: Metriche e definizioni dei livelli di servizio
        url: "/nkfsosm_service_level_metrics_and_definitions.html"
      - title: Qualità adattiva del servizio in Keystone
        url: "/aqos-kfs.html"
      - title: Fatturazione
        url: "/nkfsosm_kfs_billing.html"
      - title: Protezione dei dati
        url: "/nkfsosm_data_protection.html"
      - title: Tiering
        url: "/nkfsosm_tiering.html"
      - title: Disco non restituibile
        url: "/nkfsosm_nrd.html"
      - title: Supporto dei cittadini DEGLI STATI UNITI
        url: "/nkfsosm_uscs.html"
      - title: Keystone ed Equinix
        url: "/nkfsosm_equinix.html"
    - title: Modello operativo e responsabilità
      url: "/nkfsosm_overview.html"
    - title: Tenancy e multi-tenancy
      url: "/nkfsosm_tenancy_overview.html"
    - title: Infrastruttura Keystone
      url: "/nkfsosm_keystone_service_delivery_architecture_overview.html"
    - title: Requisiti del sito
      url: "/nkfsosm_site_requirements.html"
    - title: Operazioni
      url: "/nkfsosm_netapp_global_services_and_support_center_@gssc@.html"
    - title: Keystone e consulente digitale Active IQ
      url: "/nkfsosm-keystone-and-aiq.html"
      entries:
      - title: Visualizza e genera report da Consulente digitale Active IQ
        url: "/aiq-keystone-details.html"
  - title: Note di rilascio
    entries:
    - title: Novità
      url: "/rn_whats_new.html"
    - title: Problemi risolti
      url: "/rn_fixed_issues.html"
    - title: Problemi noti
      url: "/rn_known_issues.html"
  - title: Domande frequenti sugli abbonamenti Keystone
    url: "/nkfsfaq_overview.html"
    entries:
    - title: Abbonamenti Keystone
      url: "/nkfsfaq_keystone_subscription.html"
    - title: Dettagli dell'offerta di servizi
      url: "/nkfsfaq_service_offer_details.html"
    - title: Modello operativo
      url: "/nkfsfaq_operating_models.html"
    - title: Portale di accesso self-service/motore di servizio NetApp
      url: "/nkfsfaq_netapp_service_engine_self-service_access_portal.html"
  - title: Interfaccia Web di NetApp Service Engine
    url: "/sewebiug_overview.html"
    entries:
    - title: Account di fatturazione, abbonamenti, servizi e performance
      url: "/sewebiug_billing_accounts,_subscriptions,_services,_and_performance.html"
    - title: Inizia subito
      entries:
      - title: Panoramica
        url: "/sewebiug_getting_started_overview.html"
      - title: Effettuare l'accesso
        url: "/sewebiug_log_in_to_the_netapp_service_engine_web_interface.html"
      - title: Ruoli e operazioni di service provider e clienti
        url: "/sewebiug_partner_service_provider.html"
      - title: Selezionare il tenant
        url: "/sewebiug_select_tenant.html"
      - title: Visualizza l'interfaccia Web di NetApp Service Engine
        url: "/sewebiug_netapp_service_engine_web_interface_overview.html"
    - title: Visualizza gli abbonamenti Keystone Dashboard
      url: "/sewebiug_dashboard.html"
    - title: Visualizza fatturazione
      url: "/sewebiug_billing.html"
    - title: Lavorare con i file service
      url: "/sewebiug_working_with_file_services_overview.html"
      entries:
      - title: Visualizza server
        url: "/sewebiug_view_servers.html"
      - title: Creare un file server
        url: "/sewebiug_create_a_file_server.html"
      - title: Modificare il file server
        url: "/sewebiug_modify_file_server.html"
      - title: Eliminare il file server
        url: "/sewebiug_delete_file_server.html"
      - title: Visualizza condivisioni
        url: "/sewebiug_view_shares.html"
      - title: Creare una condivisione di file
        url: "/sewebiug_create_a_new_file_share.html"
      - title: Crea condivisione file da snapshot
        url: "/sewebiug_create_file_share_from_snapshot.html"
      - title: Modificare una condivisione file
        url: "/sewebiug_modify_a_file_share.html"
      - title: Eliminare una condivisione di file
        url: "/sewebiug_delete_a_file_share.html"
      - title: Creare un'istantanea ad hoc di una condivisione file
        url: "/sewebiug_create_adhoc_snapshot_of_a_file_share.html"
    - title: Lavorare con lo storage a blocchi
      url: "/sewebiug_working_with_block_storage_overview.html"
      entries:
      - title: Lavorare con i gruppi di host
        url: "/sewebiug_view_host_groups.html"
      - title: Visualizzare i dischi
        url: "/sewebiug_view_disks.html"
      - title: Creare un disco
        url: "/sewebiug_create_a_new_disk.html"
      - title: Creare un disco da uno snapshot
        url: "/sewebiug_create_a_disk_from_a_snapshot.html"
      - title: Modificare un disco
        url: "/sewebiug_modify_a_disk.html"
      - title: Eliminare un disco
        url: "/sewebiug_delete_a_disk.html"
      - title: Creare uno snapshot ad hoc di un disco
        url: "/sewebiug_create_an_adhoc_snapshot_of_a_disk.html"
    - title: Lavorare con lo storage a oggetti
      entries:
      - title: Panoramica
        url: "/sewebiug_working_with_object_storage_overview.html"
      - title: Visualizza bucket
        url: "/sewebiug_view_buckets.html"
      - title: Inizializzare lo storage a oggetti
        url: "/sewebiug_initialize_object_storage.html"
      - title: Creare bucket
        url: "/sewebiug_create_buckets.html"
      - title: Visualizzare il gruppo di storage a oggetti e gli utenti
        url: "/sewebiug_view_the_object_storage_group_and_users.html"
      - title: Creare un gruppo di storage a oggetti
        url: "/sewebiug_create_an_object_storage_group.html"
      - title: Modificare un gruppo di storage a oggetti
        url: "/sewebiug_modify_an_object_storage_group.html"
      - title: Eliminare un gruppo di storage a oggetti
        url: "/sewebiug_delete_an_object_storage_group.html"
      - title: Crea utente storage a oggetti
        url: "/sewebiug_create_object_storage_user.html"
      - title: Modificare un utente dello storage a oggetti
        url: "/sewebiug_modify_an_object_storage_user.html"
      - title: Creare una chiave S3 per un utente
        url: "/sewebiug_create_an_s3_key_for_a_user.html"
      - title: Eliminare una chiave S3 per un utente
        url: "/sewebiug_delete_an_s3_key_for_a_user.html"
    - title: Gestire i servizi cloud
      entries:
      - title: Gestire i servizi cloud
        entries:
        - title: Panoramica
          url: "/sewebiug_managing_subscribed_services_overview.html"
        - title: Visualizzare un elenco dei servizi sottoscritti
          url: "/sewebiug_view_a_list_of_subscribed_services.html"
        - title: Aggiungere un servizio sottoscritto
          url: "/sewebiug_add_a_subscribed_service.html"
        - title: Modificare i dettagli del servizio sottoscritto
          url: "/sewebiug_modify_the_subscribed_service_details.html"
        - title: Eliminare un servizio sottoscritto
          url: "/sewebiug_delete_a_subscribed_service.html"
      - title: Gestire Azure NetApp Files
        entries:
        - title: Gestire gli account NetApp Azure
          url: "/sewebiug_managing_azure_netapp_accounts.html"
        - title: Gestire i pool di capacità di Azure
          url: "/sewebiug_managing_azure_capacity_pools.html"
        - title: Gestire i volumi Azure
          url: "/sewebiug_managing_azure_volumes.html"
      - title: Gestire Cloud Volumes Service per la piattaforma cloud Google
        url: "/sewebiug_managing_gcp_cvs.html"
    - title: Visualizzare i report
      url: "/sewebiug_working_with_reports.html"
    - title: Eseguire il backup dei volumi
      url: "/sewebiug_back_up_file_shares_and_disks.html"
    - title: Gestire gli abbonamenti
      url: "/sewebiug_managing_subscriptions.html"
    - title: Gestire le richieste di servizio
      entries:
      - title: Panoramica
        url: "/sewebiug_managing_service_requests_overview.html"
      - title: Inoltrare una richiesta di servizio
        url: "/sewebiug_raise_a_service_request.html"
      - title: Tenere traccia di una richiesta di servizio
        url: "/sewebiug_track_a_service_request.html"
      - title: Processo di richiesta di servizio
        url: "/sewebiug_service_request_process.html"
    - title: Eseguire attività amministrative
      entries:
      - title: Gestire gli utenti
        entries:
        - title: Visualizzare un elenco di utenti
          url: "/sewebiug_view_a_list_of_users.html"
        - title: Aggiungere un utente
          url: "/sewebiug_add_a_user.html"
        - title: Modificare i dettagli dell'utente
          url: "/sewebiug_modify_user_details.html"
        - title: Eliminare un utente
          url: "/sewebiug_delete_a_user.html"
      - title: Gestire tenant e subtenant
        url: "/sewebiug_managing_tenants_and_subtenants.html"
      - title: Visualizzare e gestire gli avvisi
        url: "/sewebiug_alerts.html"
    - title: Gestire le reti
      url: "/sewebiug_define_network_configurations.html"
  - title: Riferimento API del NetApp Service Engine
    url: "/seapiref_overview_of_netapp_service_engine_apis.html"
    entries:
    - title: Autorizzazione e autenticazione
      url: "/seapiref_authorization_and_authentication.html"
    - title: API REST di NetApp Service Engine
      url: "/seapiref_netapp_service_engine_rest_apis.html"
    - title: API consumer
      entries:
      - title: Panoramica
        url: "/seapiref_consumer_apis_overview.html"
      - title: API di orchestrazione del cloud
        url: "/seapiref_cloud_orchestration_apis.html"
      - title: API per lo storage a blocchi
        url: "/seapiref_block_storage_apis.html"
      - title: API di file Services
        url: "/seapiref_file_services_apis.html"
      - title: API dello storage a oggetti
        url: "/seapiref_object_storage_apis.html"
      - title: API di backup
        url: "/seapiref_backups_apis.html"
      - title: API di reporting
        url: "/seapiref_reporting_apis.html"
      - title: Creare sottoreti utilizzando le API
        url: "/seapiref_subnets_apis.html"
      - title: API di amministrazione (consumer)
        url: "/seapiref_@consumer@_administration_apis.html"
    - title: API dell'amministratore
      entries:
      - title: Panoramica
        url: "/seapiref_administrator_apis_overview.html"
      - title: Tenant
        url: "/seapiref_tenants.html"
      - title: Subtenant
        url: "/seapiref_subtenants.html"
      - title: Utenti
        url: "/seapiref_users.html"
      - title: Zone
        url: "/seapiref_zones.html"
      - title: Regioni
        url: "/seapiref_regions.html"
      - title: Cluster ONTAP
        url: "/seapiref_ontap_clusters.html"
      - title: Istanze di StorageGRID
        url: "/seapiref_storagegrid_instances.html"
      - title: Livelli di servizio
        url: "/seapiref_service_levels.html"
      - title: Richieste di servizio
        url: "/seapiref_service_requests.html"
      - title: Lavori
        url: "/seapiref_jobs.html"
  - title: Note legali
    url: "/legal-notices.html"
