---
settings:
  name: Keystone
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: it-it,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,es-es,fr-fr
sidebar:
  entries:
  - title: Servizi NetApp Keystone
    url: "/index.html"
    entries:
    - title: Termini e descrizione del servizio
      url: "/nkfsosm_service_terms_and_description_overview.html"
      entries:
      - title: Definizioni della capacità del servizio
        url: "/nkfsosm_keystone_service_capacity_definitions.html"
      - title: Livelli di servizio in Keystone
        url: "/nkfsosm_performance.html"
      - title: Metriche e definizioni dei livelli di servizio
        url: "/nkfsosm_service_level_metrics_and_definitions.html"
      - title: Qualità adattiva del servizio in Keystone
        url: "/aqos-kfs.html"
      - title: Fatturazione
        url: "/nkfsosm_kfs_billing.html"
      - title: Protezione dei dati
        url: "/nkfsosm_data_protection.html"
      - title: Tiering
        url: "/nkfsosm_tiering.html"
      - title: Disco non restituibile
        url: "/nkfsosm_nrd.html"
      - title: Supporto dei cittadini DEGLI STATI UNITI
        url: "/nkfsosm_uscs.html"
      - title: Keystone ed Equinix
        url: "/nkfsosm_equinix.html"
    - title: Modello operativo e responsabilità
      url: "/nkfsosm_overview.html"
    - title: Tenancy e multi-tenancy
      url: "/nkfsosm_tenancy_overview.html"
    - title: Infrastruttura Keystone
      url: "/nkfsosm_keystone_service_delivery_architecture_overview.html"
    - title: Requisiti del sito
      url: "/nkfsosm_site_requirements.html"
    - title: Operazioni
      url: "/nkfsosm_netapp_global_services_and_support_center_@gssc@.html"
    - title: Keystone e consulente digitale Active IQ
      url: "/nkfsosm-keystone-and-aiq.html"
      entries:
      - title: Visualizza e genera report da Consulente digitale Active IQ
        url: "/aiq-keystone-details.html"
  - title: Note di rilascio
    entries:
    - title: Novità
      url: "/rn_whats_new.html"
    - title: Problemi risolti
      url: "/rn_fixed_issues.html"
    - title: Problemi noti
      url: "/rn_known_issues.html"
  - title: Domande frequenti sugli abbonamenti Keystone
    url: "/nkfsfaq_overview.html"
    entries:
    - title: Abbonamenti Keystone
      url: "/nkfsfaq_keystone_subscription.html"
    - title: Dettagli dell'offerta di servizi
      url: "/nkfsfaq_service_offer_details.html"
    - title: Modello operativo
      url: "/nkfsfaq_operating_models.html"
  - title: Note legali
    url: "/legal-notices.html"
