---
sidebar: sidebar 
permalink: seapiref_service_requests.html 
keywords: netapp, keystone, service, requests, 
summary: Richieste di servizio Keystone 
---
= Richieste di servizio
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utilizzare i metodi elencati nella tabella seguente per creare e recuperare le richieste di servizio.

|===


| Metodo HTTP | Percorso | Descrizione 


| `GET` | `/v2.1/tenants/{tenant_id}/servicerequests` | Recuperare le richieste di servizio. 


| `GET` | `/v2.1/tenants/{tenant_id}/servicerequests/{id}` | Recuperare una richiesta di servizio in base all'ID. 


| `POST` | `/v2.1/tenants/{tenant_id}/servicerequests/` | Creare una richiesta di servizio. 


| `GET` | `/v2.1/tenants/{tenant_id}/servicerequests/categories` | Recuperare le categorie di richieste di servizio. 
|===


== Attributi della richiesta di servizio

La tabella seguente elenca gli attributi della richiesta di servizio.

|===


| Attributo | Tipo | Descrizione 


| `Id` | Stringa | Identificativo della richiesta di servizio. Ad esempio: `SRQ0035952014.` 


| `subject` | Stringa | Oggetto della richiesta di servizio. 


| `comment` | Stringa | Un commento sulla richiesta di servizio 


| `category` | Stringa | La categoria della richiesta: Backup, disaster recovery, tecnica, altro o abbonamento. 


| `priority` | Stringa | Priorità della richiesta di servizio: Molto bassa, bassa, normale, alta o urgente. 


| `subscription` | Stringa | Il numero di abbonamento a Zuora. 


| `commitment` | –  a| 
Dettagli dell'impegno di iscrizione, tra cui:

* Service level (string) (livello di servizio): Livello di servizio: Standard, Premium o Extreme.
* New_Commitment (intero): Nuova capacità totale richiesta.




| `zone` | Stringa | Il nome della zona. 


| `subtenant_id` | Stringa | L'identificatore del sottotenant. 


| `storage_object_type` | Stringa | Tipo di oggetto di storage: File server o archivio di blocchi. 


| `storage_object_id` | Stringa | L'identificatore dell'oggetto di storage. Ad esempio:
`5d2fb0fb4f47df00015274e3` 


| `service_type` | Stringa | Il tipo di servizio: Servizi file, storage a blocchi o storage a oggetti. 
|===


== Recuperare le richieste di servizio

Utilizzare il metodo elencato nella tabella seguente per recuperare le categorie di richiesta di servizio per il tenant specificato.

|===


| Metodo HTTP | Percorso | Descrizione | Parametri 


| `GET`` | `/v2.1/tenants/{tenant_id}/servicerequests` | Recuperare le richieste di servizio. | `tenant_id`: (Facoltativo) Restituisci le richieste di servizio per il tenant specificato.
`offset` e. `limit`– vedere link:seapiref_netapp_service_engine_rest_apis.html#pagination>["Impaginazione comune"] 
|===
Attributi del corpo della richiesta richiesti: `none`

*Esempio di corpo della richiesta:*

....
none
....
*Esempio di corpo di risposta:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "total_records": 34,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 6,
    "limit": 1,
    "records": [
      {
        "id": "SRQ0035952014",
        "subject": "DR Failover - fileserver",
        "description": "catgory:Disaster Recovery Failover \n   subtenant: DefaultSubtenants2 \n  region: au-east2 \n zone: au-east2-a \n   fileserver: Demotsysserv1 \n tenant:MyOrg \n comments:comments",
        "priority": "Urgent",
        "status": "New",
        "createdDate": "2020-05-22T04:23:12+0000",
        "updatedDate": "2020-05-22T04:23:12+0000"
      }
    ]
  }
}
....


== Recuperare una richiesta di servizio in base all'ID

Utilizzare il metodo elencato nella tabella seguente per recuperare una richiesta di servizio in base all'ID della richiesta di servizio.

|===


| Metodo HTTP | Percorso | Descrizione | Parametri 


| `GET` | `/v2.1/tenants/{tenant_id}/servicerequests/{id}` | Recuperare una richiesta di servizio in base all'ID.  a| 
* `tenant_id`ID tenant
* `id`: Richiesta di servizio IDFoppure esempio: SRQ0035952014


|===
Attributi del corpo della richiesta richiesti: `none`

*Esempio di corpo della richiesta:*

....
none
....
*Esempio di corpo di risposta:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "SRQ0035952014",
        "subject": "DR Failover - fileserver",
        "description": "catgory:Disaster Recovery Failover \n   subtenant: DefaultSubtenants2 \n  region: au-east2 \n zone: au-east2-a \n   fileserver: Demotsysserv1 \n tenant:MyOrg \n comments:comments",
        "priority": "Urgent",
        "status": "New",
        "createdDate": "2020-05-22T04:23:12+0000",
        "updatedDate": "2020-05-22T04:23:12+0000"
      }
    ]
  }
}
....


== Creare una richiesta di servizio

Utilizzare il metodo elencato nella tabella seguente per creare una richiesta di servizio.

|===


| Metodo HTTP | Percorso | Descrizione | Parametri 


| `POST` | `/v2.1/tenants/{tenant_id}/servicerequests/categories` | Creare una richiesta di servizio. | `tenant_id`L'identificatore del tenant. 
|===
Attributi del corpo della richiesta richiesti: Gli attributi richiesti dipendono dalla categoria della richiesta di servizio. La tabella seguente elenca gli attributi del corpo della richiesta.

|===


| Categoria | Obbligatorio 


| Iscrizione | `subscription` e. `commitment` 


| Disaster recovery | `storage_object_type`, `subtenant_id`, e. `storage_object_id` 


| Tecnico | `subtenant_id` e. `service_type`Se `service_type` è un file service o uno storage a blocchi, è necessaria una zona. 


| Altro | Zona 
|===
*Esempio di corpo della richiesta:*

....
{
  "subject": "string",
  "comment": "string",
  "category": "subscription",
  "priority": "Normal",
  "subscription": "A-S00003969",
  "commitment": {
    "service_level": "standard",
    "new_commitment": 10
  },
  "zone": "au-east1-a",
  "subtenant_id": "5d2fb0fb4f47df00015274e3",
  "storage_object_type": "fileserver",
  "storage_object_id": "5d2fb0fb4f47df00015274e3",
  "service_type": "File Services"
}
....
*Esempio di corpo di risposta:*

....
{
  "status": {
    "user_message": "string",
    "verbose_message": "string",
    "code": "string"
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "string",
        "subject": "string",
        "description": "string",
        "status": "New",
        "priority": "Normal",
        "createdDate": "2020-05-12T03:18:25+0000",
        "UpdatedDate": "2020-05-12T03:18:25+0000"
      }
    ]
  }
....


== Recuperare le categorie di richieste di servizio

La tabella seguente elenca le categorie di richieste di servizio di recupero per un tenant specificato.

|===


| Metodo HTTP | Percorso | Descrizione | Parametri 


| `GET` | `/v2.1/tenants/{tenant_id}/servicerequests/categories` | Recuperare le categorie di richieste di servizio. | `tenant_id:` (Facoltativo) Restituisci le richieste di servizio per un tenant specificato. 
|===
Attributi del corpo della richiesta richiesti: `none`

*Esempio di corpo della richiesta:*

....
none
....
*Esempio di corpo di risposta:*

....
{
  "status": {
    "user_message": "Okay. Returned 5 records.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 5,
    "records": [
      {
        "key": "dr",
        "value": "Disaster Recovery Failover"
      },
      {
        "key": "technical",
        "value": "Technical Issue"
      },
      {
        "key": "other",
        "value": "Other"
      },
      {
        "key": "subscription",
        "value": "Subscription Management"
      },
      {
        "key": "backup",
        "value": "Backup Restore"
      }
    ]
  }
}
....