---
sidebar: sidebar 
permalink: seapiref_reporting_apis.html 
keywords: netapp, keystone, reporting, apis, 
summary: API di reporting Keystone 
---
= API di reporting
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utilizzare i metodi descritti nella tabella seguente per recuperare e generare i report.

|===
| Metodo HTTP | Percorso | Descrizione 


| `GET` | `/v2.1/reports` | Recuperare tutti gli elenchi di report. 


| `POST` | `/v2.1/reports/{filename}` | Recuperare un report. 
|===


== Recuperare un elenco di report

Utilizzare il metodo riportato nella tabella seguente per recuperare un elenco di report.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `GET` | `/v2.1/reports` | Recuperare tutti i report disponibili per un tenant. I report possono essere filtrati in base all'intervallo di date.  a| 
* `tenant_id (string)`
* `start(string)`: Recupera report più recenti della data specificata in inizio.
* `end (string)`: Recupera i report precedenti alla data specificata in fine


|===
Attributi del corpo della richiesta richiesti: `none`

*Esempio di corpo della richiesta:*

....
none
....
*Esempio di corpo di risposta:*

....
{
  "status": {
    "user_message": "string",
    "verbose_message": "string",
    "code": "string"
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "filename": "string"
      }
    ]
  }
}
....


=== Recuperare un report identificato dal nome del file

Utilizzare il metodo riportato nella tabella seguente per recuperare un report identificato dal nome del file.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `GET` | `/v2.1/reports/{filename}` | Recuperare un report identificato dal nome del file. | `filename (string)`: Il nome del file di report. 
|===
Attributi del corpo della richiesta richiesti: `none`

*Esempio di corpo della richiesta:*

....
none
....
*Esempio di corpo di risposta:*

....
{
  "status": {
    "user_message": "string",
    "verbose_message": "string",
    "code": "string"
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "filename": "string"
      }
    ]
  }
}
....