---
sidebar: sidebar 
permalink: seapiref_jobs.html 
keywords: netapp, keystone, jobs, 
summary: API di Keystone Jobs 
---
= Lavori
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utilizzare le API di job per esaminare i dettagli del lavoro. Per ulteriori informazioni sull'utilizzo dei lavori, vedere API oggetti di lavoro e processi asincroni.



== Recuperare i lavori

Utilizzare il metodo elencato nella tabella seguente per recuperare tutti i lavori o un sottoinsieme di tali lavori. Specificare un `tenant_id` restituisce solo i job appartenenti a quel tenant.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `GET` | `/v2.1/jobs` | Recuperare i lavori. | `tenant_id`: (Facoltativo) Restituisci gli archivi di blocchi appartenenti al tenant specificato.
`offset` e. `limit`– vedere link:seapiref_netapp_service_engine_rest_apis.html#pagination>["Impaginazione comune"] 
|===
Attributi del corpo della richiesta richiesti: `none`

*Esempio di corpo della richiesta:*

....
none
....
*Esempio di corpo di risposta:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "total_records": 2625,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 0,
    "limit": 1,
    "records": [
      {
        "id": "5ed72c8c6342e90001439d54",
        "action": "create",
        "job_summary": "Create request is successfully submitted",
        "created": "2020-06-03T04:52:28.478Z",
        "updated": "2020-06-03T04:52:32.636Z",
        "object_id": "5ed72c8c6342e90001439d55",
        "object_type": "sg_buckets",
        "object_name": "test1234",
        "status": "successful",
        "status_detail": "Creation of s3 bucket 'test1234' completed successfully.",
        "last_error": "",
        "user_id": "5e85225af038943eb4b74684",
        "job_tasks": [
          {
            "id": "5ed72c8c6342e90001439d57",
            "job_id": "5ed72c8c6342e90001439d54",
            "action": "create",
            "driver": "storagegrid_ansible",
            "object_id": "5ed72c8c6342e90001439d55",
            "object_type": "sg_buckets",
            "resource_type": "sg_bucket",
            "status": "successful",
            "status_detail": "Worker completed task successfully.",
            "last_error": "",
            "user_id": "5e85225af038943eb4b74684",
            "request_payload": {
              "grid_account_id": "05336917559886003354",
              "grid_admin_base_url": "https://sggmi-dev.dev.ausngs.netapp.au/api/v3",
              "org_password": "netapp01",
              "org_username": "root",
              "s3_bucket_name": "test1234"
            }
          }
        ]
      }
    ]
  }
}
....


=== Recuperare un lavoro in base all'ID lavoro

Utilizzare il metodo elencato nella tabella seguente per recuperare un lavoro in base all'ID.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `GET` | `/v2.1/jobs/{id}` | Recuperare un lavoro in base all'ID. | `id (string)`L'identificatore univoco del lavoro. 
|===
Attributi del corpo della richiesta richiesti: `job identifier`

*Esempio di corpo della richiesta:*

....
none
....
*Esempio di corpo di risposta:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "id": "5e66f18e09a74c0001b89640",
        "action": "create",
        "job_summary": "Create S3 bucket for Sub Tenant",
        "created": "2020-03-10T01:46:54.097Z",
        "updated": "2020-03-10T01:46:57.664Z",
        "object_id": "5e66f18e09a74c0001b89641",
        "object_type": "sg_buckets",
        "status": "successful",
        "status_detail": "Creation of s3 bucket 'mys3bucket' completed successfully.",
        "last_error": "",
        "user_id": "5bbee380a2df7a04d43acaee",
        "job_tasks": [
          {
            "id": "5e66f18e09a74c0001b89642",
            "job_id": "5e66f18e09a74c0001b89640",
            "action": "create",
            "driver": "storagegrid_ansible",
            "object_id": "5e66f18e09a74c0001b89641",
            "object_type": "sg_buckets",
            "resource_type": "sg_bucket",
            "status": "successful",
            "status_detail": "Worker completed task successfully.",
            "last_error": "",
            "user_id": "5bbee380a2df7a04d43acaee",
            "request_payload": {
              "grid_account_id": "47490102387197219062",
              "grid_admin_base_url": "https://sggmi-dev.dev.ausngs.netapp.au/api/v3",
              "org_password": "netapp01",
              "org_username": "root",
              "s3_bucket_name": "mys3bucket"
            }
          }
        ]
      }
    ]
  }
}
....


== API degli oggetti di lavoro e processi asincroni

Alcune delle chiamate API, in particolare quelle utilizzate per l'aggiunta o la modifica delle risorse, possono richiedere più tempo per il completamento rispetto ad altre chiamate. NetApp Service Engine elabora queste richieste a esecuzione prolungata in modo asincrono.

Dopo aver effettuato una chiamata API eseguita in modo asincrono, il codice di risposta HTTP 202 indica che la richiesta è stata convalidata e accettata correttamente, ma non ancora completata. La richiesta viene elaborata come attività in background che continua a essere eseguita dopo la risposta HTTP iniziale al client. La risposta include l'oggetto job che ancora la richiesta, incluso il relativo identificatore univoco.



=== Esecuzione di query sull'oggetto lavoro associato a una richiesta API

L'oggetto di lavoro restituito nella risposta HTTP contiene diverse proprietà. È possibile eseguire una query sulla proprietà state per determinare se la richiesta è stata completata correttamente. Un oggetto lavoro può trovarsi in uno dei seguenti stati:

* NORMALE
* ATTENZIONE
* INSUCCESSI_PARZIALI
* ERRORE


Esistono due tecniche che è possibile utilizzare quando si esegue il polling di un oggetto di lavoro per rilevare uno stato terminale per l'attività, ovvero riuscito o non riuscito:

* Richiesta di polling standard: Lo stato corrente del processo viene restituito immediatamente.
* Richiesta di polling lunga: Quando lo stato del processo passa A NORMAL, ERROR o PARTIAL_FAILURES.




=== Passaggi per una richiesta asincrona

È possibile utilizzare la seguente procedura di alto livello per completare una chiamata API asincrona:

. Eseguire la chiamata API asincrona.
. Ricevere una risposta HTTP 202 che indichi la corretta accettazione della richiesta.
. Estrarre l'identificatore per l'oggetto di lavoro dal corpo della risposta.
. All'interno di un loop, attendere che l'oggetto job raggiunga lo stato di terminale NORMAL, ERROR o PARTIAL_FAILURES.
. Verificare lo stato terminale del lavoro e recuperare il risultato del lavoro.

