---
sidebar: sidebar 
permalink: seapiref_service_levels.html 
keywords: netapp, keystone, service, levels, 
summary: Livelli di servizio Keystone 
---
= Livelli di servizio
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utilizzare i metodi elencati nella tabella seguente per recuperare, creare, modificare ed eliminare i livelli di servizio.

|===
| Metodo HTTP | Percorso | Descrizione 


| `GET` | `/v2.1/servicelevels` | Recuperare tutti i livelli di servizio. 


| `GET` | `/v2.1/servicelevels/{id}` | Recuperare un livello di servizio in base all'ID. 


| `POST` | `/v2.1/servicelevels` | Creare un nuovo livello di servizio. 


| `PUT` | `/v2.1/servicelevels/{id}` | Modificare i dettagli del livello di servizio in base all'ID. 


| `DELETE` | `/v2.1/servicelevels/{id}` | Eliminare un livello di servizio. 
|===


== Attributi del livello di servizio

La tabella seguente elenca gli attributi del livello di servizio.

|===
| Attributo | Tipo | Descrizione 


| `id` | Stringa | Identificatore univoco del livello di servizio. 


| `name` | Stringa | Il nome del livello di servizio. 


| `description` | Stringa | La descrizione del livello di servizio. 


| `policy_name` | Stringa | Nome della qualità del servizio (QoS) del livello di servizio. Valori consentiti: nse_value, nse_standard, nse_performance e nse_Extreme. 


| `available` | Booleano | Indica se il livello di servizio è disponibile per l'utilizzo. 


| `grandfathered` | Booleano | Indica se il livello di servizio è stato ritirato. 


| `peak_iops_per_tb` | Intero | Il massimo IOPS possibile per TIB. 


| `expected_iops_per_tb` | Intero | Gli IOPS minimi previsti per TIB. 


| `absolute_min_iops` | Intero | IOPS minimo assoluto utilizzato come override quando gli IOPS previsti sono inferiori a questo valore. 


| `peak_iops_allocation` | Stringa | L'allocazione IOPS massima. Valori consentiti: Allocated_space e used_space. 


| `io_block_size_kb` | Intero | La dimensione del blocco i/o (KiB). 


| `min_size_gb` | Intero | La dimensione minima (GiB). 


| `max_size_gb` | Intero | La dimensione massima (GiB). 


| `max_peak_iops` | Intero | IOPS massimi per il livello di servizio. 


| `max_expected_iops` | Intero | Il massimo IOPS previsto. 


| `autogrow_max_percent` | Intero | Percentuale massima di crescita automatica. 


| `ontap_aggregates` | –  a| 
L'elenco degli aggregati ONTAP. Un aggregato ONTAP è costituito da:

* `cluster_UIID: ONTAP cluster UUID`
* `aggr_name: ONTAP aggregate name`
* `aggr_uuid: ONTAP aggregate UUID`
* `node_name: ONTAP cluster node name`Ad esempio:


[listing]
----
"ontap_aggregates": [
    {
      "cluster_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "aggr_name": "string",
      "aggr_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "node_name": "node01"
    }
  ]
----


| `primary_volume_defaults` | –  a| 
* Snapshot_auto_delete_target_free_space (intero): Questa opzione specifica la percentuale di spazio libero alla quale deve terminare l'eliminazione automatica delle copie Snapshot.
* auto_size_mode (string): La modalità di dimensionamento automatico del volume. Valori consentiti: OFF, Grow, grow_shrink ad esempio:


[listing]
----
"primary_volume_defaults": {    "snapshot_auto_delete_target_free_space": 3,    "auto_size_mode": "grow_shrink"
----
|===


== Recuperare i livelli di servizio

Utilizzare il metodo elencato nella tabella seguente per recuperare tutti i livelli di servizio.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `GET` | `/v2.1/servicelevels` | Recuperare tutti i livelli di servizio. | Nessuno 
|===
Attributi del corpo della richiesta richiesti: `none`

*Esempio di corpo della richiesta:*

....
none
....
*Esempio di corpo di risposta:*

....
{
  "status": {
    "user_message": "Okay. Returned 3 records.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "total_records": 3,
    "records": [
      {
        "name": "standard",
        "description": "Best suited for general purpose workloads",
        "slo": "1000IOPS/TB",
        "min_size": 137438953472,
        "io_block_size_kb": 32,
        "min_size_gb": 10,
        "max_size_gb": 40960,
        "min_iops": 100,
        "peak_iops_per_tb": 1000,
        "expected_iops_per_tb": 700,
        "max_peak_iops": 40000,
        "max_expected_iops": 28000,
        "max_peak_throughput": 1250,
        "max_expected_throughput": 875
      },
      {
        "name": "extreme",
        "description": "Best suited for performance-critical workloads",
        "slo": "12000IOPS/TB",
        "min_size": 91625968981,
        "io_block_size_kb": 32,
        "min_size_gb": 10,
        "max_size_gb": 10240,
        "min_iops": 500,
        "peak_iops_per_tb": 12000,
        "expected_iops_per_tb": 8000,
        "max_peak_iops": 120000,
        "max_expected_iops": 60000,
        "max_peak_throughput": 3750,
        "max_expected_throughput": 1875
      },
      {
        "name": "premium",
        "description": "Best suited for databases and high performance workloads",
        "slo": "4000IOPS/TB",
        "min_size": 137438953472,
        "io_block_size_kb": 32,
        "min_size_gb": 10,
        "max_size_gb": 10240,
        "min_iops": 300,
        "peak_iops_per_tb": 4000,
        "expected_iops_per_tb": 3000,
        "max_peak_iops": 40000,
        "max_expected_iops": 30000,
        "max_peak_throughput": 1250,
        "max_expected_throughput": 937
      }
    ]
  }
}
....


== Recuperare i livelli di servizio in base al nome

Utilizzare il metodo elencato nella tabella seguente per recuperare i livelli di servizio in base al nome.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `GET` | `/v2.1/servicelevels/{name}` | Recuperare un livello di servizio in base al nome. | `name (string)`: Il nome del livello di servizio. 
|===
Attributi del corpo della richiesta richiesti: `none`

*Esempio di corpo della richiesta:*

....
none
....
*Esempio di corpo di risposta:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "name": "premium",
        "description": "Best suited for databases and high performance workloads",
        "slo": "4096IOPS/TB",
        "min_size": 137438953472,
        "io_block_size_kb": 32,
        "min_size_gb": 10,
        "max_size_gb": 10240,
        "min_iops": 300,
        "peak_iops_per_tb": 4096,
        "expected_iops_per_tb": 3000,
        "max_peak_iops": 40000,
        "max_expected_iops": 30000,
        "max_peak_throughput": 1250,
        "max_expected_throughput": 937
      }
    ]
  }
}
....


== Creare un livello di servizio

Utilizzare il metodo elencato nella tabella seguente per creare un livello di servizio.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `POST` | `/v2.1/servicelevels` | Creare un livello di servizio. | Nessuno 
|===
Attributi del corpo della richiesta richiesti: `name`, `policy_name`

*Esempio di corpo della richiesta:*

....
{
  "name": "MyServiceLevelName",
  "description": "My new service level description",
  "policy_name": "nse_value",
  "available": true,
  "grandfathered": false,
  "peak_iops_per_tb": 1000,
  "expected_iops_per_tb": 700,
  "absolute_min_iops": 100,
  "peak_iops_allocation": "allocated_space",
  "io_block_size_kb": 32,
  "min_size_gb": 10,
  "max_size_gb": 40960,
  "max_peak_iops": 20000,
  "max_expected_iops": 5000,
  "autogrow_max_percent": 3,
  "ontap_aggregates": [
    {
      "cluster_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "aggr_name": "string",
      "aggr_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "node_name": "node01"
    }
  ],
  "primary_volume_defaults": {
    "snapshot_auto_delete_target_free_space": 3,
    "auto_size_mode": "grow_shrink"
  }
}
....
*Esempio di corpo di risposta:*

....
{
  "status": {
    "user_message": "Okay. New resource created.",
    "verbose_message": "",
    "code": 201
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "name": "MyServiceLevelName",
        "description": "My new service level description",
        "slo": "1000IOPS/TB",
        "min_size": 0,
        "io_block_size_kb": 32,
        "min_size_gb": 10,
        "max_size_gb": 40960,
        "min_iops": 100,
        "peak_iops_per_tb": 1000,
        "expected_iops_per_tb": 700,
        "max_peak_iops": 20000,
        "max_expected_iops": 5000,
        "max_peak_throughput": 625,
        "max_expected_throughput": 156
      }
    ]
  }
}
....


== Modificare un livello di servizio

Per modificare un livello di servizio, utilizzare il metodo riportato nella tabella seguente.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `PUT` | `/v2.1/servicelevels/{name}` | Modificare i dettagli di un livello di servizio. | `name (string)`: Il nome del livello di servizio. 
|===
Attributi del corpo della richiesta richiesti: `none`

*Esempio di corpo della richiesta:*

....
{
  "name": "MyNewServiceLevelName",
  "description": "Service level description",
  "policy_name": "nse_value",
  "available": false,
  "grandfathered": false,
  "peak_iops_per_tb": 1000,
  "expected_iops_per_tb": 700,
  "absolute_min_iops": 100,
  "peak_iops_allocation": "allocated_space",
  "io_block_size_kb": 32,
  "min_size_gb": 10,
  "max_size_gb": 40960,
  "max_peak_iops": 20000,
  "max_expected_iops": 5000,
  "autogrow_max_percent": 3,
  "ontap_aggregates": [
    {
      "cluster_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "aggr_name": "string",
      "aggr_uuid": "3fa85f64-5717-4562-b3fc-2c963f66afa6",
      "node_name": "node01"
    }
  ],
  "primary_volume_defaults": {
    "snapshot_auto_delete_target_free_space": 3,
    "auto_size_mode": "grow_shrink"
  }
}
....
*Esempio di corpo di risposta:*

....
TBA
....


== Eliminare il livello di servizio per ID

Utilizzare il metodo elencato nella tabella seguente per eliminare un livello di servizio in base all'ID.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `DELETE` | `/v2.1/servicelevels/{name}` | Eliminare il livello di servizio identificato dall'ID. | `name (string)`: Il nome del livello di servizio. 
|===
*Esempio di corpo della richiesta:*

....
none
....
*Esempio di corpo di risposta:*

....
No content for succesful delete
....