---
sidebar: sidebar 
permalink: seapiref_block_storage_apis.html 
keywords: netapp, keystone, block storage, block stores, disks, host groups, initiators, apis 
summary: API per lo storage a blocchi Keystone 
---
= API per lo storage a blocchi
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile utilizzare le API dello storage a blocchi per visualizzare e gestire lo storage a blocchi.

Prima di creare dischi, è necessario creare archivi a blocchi. Quando si crea un disco, è necessario creare un gruppo di host o selezionare un gruppo di host esistente per accedere al disco. Per ulteriori informazioni, vedere link:sewebiug_working_with_block_storage_overview.html["Lavorare con lo storage a blocchi"].



== Blocca i negozi

È possibile utilizzare le API di archiviazione a blocchi per recuperare e gestire gli archivi a blocchi.

[cols="1,1,3,2"]
|===
| Verbo HTTP | Percorso | Descrizione | Parametri obbligatori/corpo della richiesta 


 a| 
`GET`
 a| 
`/v2.1/blockstores`
| Puoi recuperare i dettagli di tutti i tuoi block store. Recupera i dettagli degli archivi a blocchi, come ID archivio a blocchi, indirizzo IP, regione, zona, ID subnet, e tag.  a| 
`offset`: Il numero di elementi da saltare prima di iniziare a raccogliere il set di risultati.
`limit`: Il numero di elementi da restituire.



 a| 
`GET`
 a| 
`/v2.1/blockstores/{id}`
| È possibile recuperare i dettagli di uno specifico archivio di blocchi. Recupera i dettagli dell'archivio di blocchi, ad esempio indirizzo IP, regione, zona, ID subnet e tag in base all'ID immesso.  a| 
`id`: L'ID dell'archivio di blocchi.



 a| 
`POST`
 a| 
`/v2.1/blockstores`
| È possibile creare un archivio di blocchi. Aggiungere i valori nel corpo della richiesta per creare un archivio di blocchi con i parametri specificati, ad esempio il protocollo di servizio, l'ID del sottenant, la zona, l'ID della subnet e i tag.  a| 
`subtenant_id`: L'ID del subtenant.
`zone`: Il nome della zona.
`subnet_id`: L'ID della subnet.



 a| 
`POST`
 a| 
`/v2.1/blockstores/{id}/`
`tags`
| È possibile creare o sostituire tag per un archivio di blocchi. Aggiungere l'ID dell'archivio di blocchi e i valori dei tag nel formato "coppia chiave:valore" nel corpo della richiesta.  a| 
`id`: L'ID dell'archivio di blocchi.



 a| 
`PUT`
 a| 
`/v2.1/blockstores/{id}`
| È possibile modificare qualsiasi archivio di blocchi in base al relativo ID. Aggiungere l'ID dell'archivio blocchi e i valori che si desidera modificare nel corpo della richiesta, ad esempio zone, protocollo di servizio e tag.  a| 
`id`: L'ID dell'archivio di blocchi.



 a| 
`DELETE`
 a| 
`/v2.1/blockstores/{id}`
 a| 
È possibile eliminare qualsiasi archivio di blocchi in base al relativo ID.
 a| 
`id`: L'ID dell'archivio di blocchi.

|===

NOTE: Prima di eliminare un archivio di blocchi, è necessario eliminare tutti i dischi ad esso mappati.



== Dischi

È possibile utilizzare le API dei dischi per recuperare e gestire i dischi.

[cols="1,1,3,2"]
|===
| Verbo HTTP | Percorso | Descrizione | Parametri obbligatori/corpo della richiesta 


 a| 
`GET`
 a| 
`/v2.1/disks`
| È possibile recuperare i dettagli di tutti i dischi. Recupera i dettagli dei dischi, ad esempio ID archivio blocchi, nome, percorso del disco, protocollo, policy di snapshot, e tag.  a| 
`offset`: Il numero di elementi da saltare prima di iniziare a raccogliere il set di risultati.
`limit`: Il numero di elementi da restituire.



 a| 
`GET`
 a| 
`/v2.1/disks/{id}`
| È possibile recuperare i dettagli di un disco specifico. Recupera i dettagli del disco, ad esempio ID archivio blocchi, nome, percorso del disco, protocollo, policy di snapshot, E i tag in base all'ID inserito.  a| 
`id`: L'ID del disco.



 a| 
`POST`
 a| 
`/v2.1/disks`
| È possibile creare un disco. Aggiungere i valori nel corpo della richiesta per creare un disco con i parametri specificati, ad esempio ID del sottotenant, zona, nome, percorso del disco, policy di snapshot, policy di backup e tag.  a| 
`subtenant_id`: L'ID del subtenant.
`zone`: Il nome della zona.
`name`: Il nome del disco.
`disk_path`Il percorso del disco.
`protocol`: Il protocollo di storage utilizzato per l'accesso ai dispositivi a blocchi.
`os_type`: Il tipo di sistema operativo host.
`hostgroup_mappings`: I mapping dei gruppi di host.
`service_level`: Il nome del livello di servizio applicabile: Standard, Premium, Premium-Tiering, Extreme o Extreme-Tiering.
`size_gb`: Le dimensioni del disco in GB.



 a| 
`POST`
 a| 
`/v2.1/disks/{id}/`
`snapshot/{name}`
| È possibile creare un'istantanea di un disco.  a| 
`id`: L'ID del disco.
`name`: Il nome dello snapshot.



 a| 
`POST`
 a| 
`/v2.1/disks/{id}/`
`tags`
| È possibile creare o sostituire tag per un disco. Aggiungere l'ID del disco e i valori per i tag nel formato "coppia chiave:valore" nel corpo della richiesta.  a| 
`id`: L'ID del disco.



 a| 
`PUT`
 a| 
`/v2.1/disks/{id}`
| È possibile modificare qualsiasi disco in base al relativo ID. Aggiungere l'ID del disco e i valori che si desidera modificare nel corpo della richiesta, ad esempio nome, livello di servizio, policy di snapshot, policy di backup e tag.  a| 
`id`: L'ID del disco.
`hostgroup_mappings`: I mapping dei gruppi di host.



 a| 
`DELETE`
 a| 
`/v2.1/disks/{id}`
| È possibile eliminare qualsiasi disco in base al relativo ID.  a| 
`id`: L'ID del disco.



 a| 
`DELETE`
 a| 
`/v2.1/disks/{id}/`
`snapshot/{name}`
| È possibile eliminare qualsiasi snapshot di un disco in base all'ID del disco e al nome dello snapshot.  a| 
`id`: L'ID del disco.
`name`: Il nome dello snapshot.

|===


== Gruppi di host

Il controllo degli accessi ai dischi viene gestito con gruppi di host. È possibile recuperare e gestire i gruppi di host utilizzando le API dei gruppi di host.

[cols="1,1,3,2"]
|===
| Verbo HTTP | Percorso | Descrizione | Parametri obbligatori/corpo della richiesta 


 a| 
`GET`
 a| 
`/v2.1/hostgroups`
| È possibile recuperare i dettagli di tutti i gruppi di host. Recupera i dettagli dei gruppi di host, ad esempio nome, dettagli del sottotenant, dettagli del tenant, zona, protocollo, iniziatori, dischi che utilizzano il gruppo host e tag.  a| 
`offset`: Il numero di elementi da saltare prima di iniziare a raccogliere il set di risultati.
`limit`: Il numero di elementi da restituire.



 a| 
`GET`
 a| 
`/v2.1/hostgroups/{id}`
| È possibile recuperare i dettagli di un gruppo host specifico. Recupera i dettagli del gruppo di host, come nome, dettagli del sottotenant, dettagli del tenant, zona, protocollo, iniziatori, dischi che utilizzano i gruppi di host e tag in base all'ID immesso.  a| 
`id`: L'ID del gruppo host.



 a| 
`POST`
 a| 
`/v2.1/hostgroups`
| È possibile creare un gruppo di host. Aggiungere i valori nel corpo della richiesta per creare un gruppo di host con i parametri specificati, ad esempio nome, ID del sottotenant, zona, protocollo, iniziatori e tag.  a| 
`name`: Il nome del gruppo di host.
`subtenant_id`: L'ID del subtenant.
`zone`: Il nome della zona.
`protocol`: Il protocollo di storage utilizzato per l'accesso ai dispositivi a blocchi.
`os_type`: Il tipo di sistema operativo host.



 a| 
`POST`
 a| 
`/v2.1/hostgroups/{id}/`
`tags`
| È possibile creare o sostituire tag per un gruppo di host. Aggiungere l'ID del gruppo host e i valori dei tag nel formato "coppia chiave:valore" nel corpo della richiesta.  a| 
`id`: L'ID del gruppo host.



 a| 
`DELETE`
 a| 
`/v2.1/hostgroups/{id}`
| È possibile eliminare qualsiasi gruppo di host in base al relativo ID.  a| 
`id`: L'ID del gruppo host.

|===


== Iniziatori in un gruppo di host

È possibile utilizzare le API dei gruppi di host per recuperare e gestire gli iniziatori mappati ai gruppi di host.

[cols="1,1,3,2"]
|===
| Verbo HTTP | Percorso | Descrizione | Parametri obbligatori/corpo della richiesta 


 a| 
`GET`
 a| 
`/v2.1/hostgroups/{id}/`
`initiators`
| È possibile recuperare i dettagli di tutti gli iniziatori. Recupera gli iniziatori e i relativi alias.  a| 
`id`: L'ID del gruppo host.



 a| 
`GET`
 a| 
`/v2.1/hostgroups/{id}/`
`initiators/{alias}`
| È possibile recuperare i dettagli di un iniziatore specifico. Recupera l'iniziatore in base all'ID e all'alias immessi.  a| 
`id`: L'ID del gruppo host.
`alias`: Il nome alias dell'iniziatore.



 a| 
`POST`
 a| 
`/v2.1/hostgroups/{id}/`
`initiators`
 a| 
È possibile creare un iniziatore per un gruppo host. Aggiungere i valori per l'iniziatore e il relativo alias nel corpo della richiesta per creare un iniziatore per il gruppo host.
 a| 
`id`: L'ID del gruppo host.
`alias`: Il nome alias dell'iniziatore.
`initiator`: L'iniziatore (nomi qualificati iSCSI o WWPN FC).



 a| 
`PATCH`
 a| 
`/v2.1/hostgroups/{id}/`
`initiators/{alias}`
| È possibile modificare un iniziatore. Aggiungere il nuovo iniziatore nel corpo della richiesta.  a| 
`id`: L'ID del gruppo host.
`alias`: Il nome alias dell'iniziatore.
`initiator`: L'iniziatore (nomi qualificati iSCSI o WWPN FC).`



 a| 
`DELETE`
 a| 
`/v2.1/hostgroups/{id}/`
`initiators/{alias}`
 a| 
È possibile eliminare un iniziatore in base all'ID del gruppo di host e all'alias dell'iniziatore.
 a| 
`id`: L'ID del gruppo host.
`alias`: Il nome alias dell'iniziatore.

|===
[NOTE]
====
Quando si aggiungono iniziatori a un gruppo host, l'iniziatore deve corrispondere al protocollo del gruppo host. Utilizzare gli IQN per i gruppi di host con protocollo iSCSI e le WWPN per i gruppi di host con protocollo FC.

L'eliminazione di un iniziatore da un gruppo di host influisce su tutti i dischi a cui è associato il gruppo di host.

====