---
sidebar: sidebar 
permalink: seapiref_file_services_apis.html 
keywords: netapp, keystone, file services, file servers, file shares, apis 
summary: API di servizi file Keystone 
---
= API di file Services
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile utilizzare le API di file Services per visualizzare e gestire i file server e le condivisioni di file.

Prima di creare condivisioni di file, è necessario creare file server per ospitarle.



== API dei file server

È possibile utilizzare le API dei file server per visualizzare e gestire i file server. Per ulteriori informazioni sui file server, vedere link:sewebiug_create_a_file_server.html["Creare un file server"].

[cols="1,1,3,2"]
|===
| Verbo HTTP | Percorso | Descrizione | Parametri obbligatori/corpo della richiesta 


 a| 
`GET`
 a| 
`/v2.1/fileservers`
| È possibile recuperare i dettagli di tutti i file server. Recupera i dettagli dei file server, ad esempio ID file server, nome, regione, zona, tenant, e tag.  a| 
`offset`: Il numero di elementi da saltare prima di iniziare a raccogliere il set di risultati.
`limit`: Il numero di elementi da restituire.



 a| 
`GET`
 a| 
`/v2.1/fileservers/{id}`
| È possibile recuperare i dettagli di un file server specifico. Recupera i dettagli del file server, ad esempio nome, regione, zona, tenant, E i tag in base all'ID inserito.  a| 
`id`: L'ID del file server.



 a| 
`POST`
 a| 
`/v2.1/fileservers`
| È possibile creare un file server. Aggiungere i valori nel corpo della richiesta per creare un file server con i parametri specificati, ad esempio nome, ID del sottenant, zona, ID della subnet.  a| 
`name`: Il nome del file server.
`subtenant_id`: L'ID del subtenant.
`zone`: Il nome della zona.
`subnet_id`: L'ID della subnet.



 a| 
`POST`
 a| 
`/v2.1/fileservers/{id}/`
`tags`
| È possibile creare o sostituire tag per un file server. Aggiungere l'ID del file server e i valori per i tag nel formato "coppia chiave:valore" nel corpo della richiesta.  a| 
`id`: L'ID del file server.



 a| 
`PUT`
 a| 
`/v2.1/fileservers/{id}`
| È possibile modificare qualsiasi file server in base al relativo ID. Aggiungere l'ID del file server e i valori che si desidera modificare nel corpo della richiesta, ad esempio nome, protocollo, zona, regione e tag.  a| 
`id`: L'ID del file server.



 a| 
`DELETE`
 a| 
`/v2.1/fileservers/{id}`
 a| 
È possibile eliminare qualsiasi file server in base al relativo ID.
 a| 
`id`: L'ID del file server.

|===
[NOTE]
====
Prima di eliminare un file server, è necessario eliminare tutte le condivisioni di file ad esso associate.

Dopo aver eliminato i file server CIFS, l'oggetto computer di Active Directory rimane. Chiedere all'amministratore di Active Directory di rimuovere manualmente l'oggetto computer per il file server cancellato da Active Directory.

====


== API di condivisione file

È possibile utilizzare le API delle condivisioni file per visualizzare e gestire le condivisioni file. Per ulteriori informazioni sulle condivisioni di file, vedere link:sewebiug_create_a_new_file_share.html["Creare una condivisione di file"].

[cols="1,1,3,2"]
|===
| Verbo HTTP | Percorso | Descrizione | Parametri obbligatori/corpo della richiesta 


 a| 
`GET`
 a| 
`/v2.1/fileshares`
| È possibile recuperare i dettagli di tutte le condivisioni di file. Recupera i dettagli delle condivisioni di file, come ID, nome, policy di snapshot, protocolli, IP del file server e tag.  a| 
`offset`: Il numero di elementi da saltare prima di iniziare a raccogliere il set di risultati.
`limit`: Il numero di elementi da restituire.



 a| 
`GET`
 a| 
`/v2.1/fileshares/{id}`
| È possibile recuperare i dettagli di una condivisione file specifica. Recupera i dettagli della condivisione file, ad esempio ID, nome, policy di snapshot, protocolli, IP del file server, E i tag in base all'ID inserito.  a| 
`id`: L'ID della condivisione del file.



 a| 
`POST`
 a| 
`/v2.1/fileshares`
| È possibile creare una condivisione file. Aggiungere i valori nel corpo della richiesta per creare una condivisione file con i parametri specificati, ad esempio ID, nome, policy di snapshot, protocolli, IP del file server e tag.  a| 
`name`: Il nome della condivisione file.
`share_path`Il percorso della condivisione file.
`fileserver_id`: L'ID del file server.
`size_gb`: La dimensione della condivisione file in Gibs.
`service_level`: Il nome del livello di servizio applicabile: Standard, Premium, Premium-Tiering, Extreme o Extreme-Tiering.
`protocol`: Il protocollo utilizzato per accedere alla condivisione file (NFS, CIFS o multiprotocollo).
`security_style`: Lo stile di sicurezza (Unix o NTFS).
`export_policy`: La policy di esportazione della condivisione file.



 a| 
`POST`
 a| 
`/v2.1/fileshares/{id}/`
`snapshot/{name}`
| È possibile creare un'istantanea di una condivisione file.  a| 
`id`: L'ID della condivisione del file.
`name`: Il nome dello snapshot.



 a| 
`POST`
 a| 
`/v2.1/fileshares/{id}/`
`tags`
| È possibile creare o sostituire tag per una condivisione file. Aggiungere l'ID della condivisione file e i valori dei tag nel formato "coppia chiave:valore" nel corpo della richiesta.  a| 
`id`: L'ID della condivisione del file.



 a| 
`PUT`
 a| 
`/v2.1/fileshares/{id}`
| È possibile modificare qualsiasi condivisione di file in base al relativo ID. Aggiungere l'ID del file server e i valori che si desidera modificare nel corpo della richiesta, ad esempio nome, protocollo, policy di snapshot, policy di backup e tag.  a| 
`id`: L'ID della condivisione del file.
`name`: Il nome della condivisione file.
`size_gb`: La dimensione della condivisione file in Gibs.
`service_level`: Il nome del livello di servizio applicabile: Standard, Premium, Premium-Tiering, Extreme o Extreme-Tiering.
`protocol`: Il protocollo utilizzato per accedere alla condivisione file (NFS, CIFS o multiprotocollo).
`export_policy`: La policy di esportazione della condivisione file.



 a| 
`DELETE`
 a| 
`/v2.1/fileshares/{id}`
| È possibile eliminare qualsiasi condivisione di file in base al relativo ID.  a| 
`id`: L'ID della condivisione del file.



 a| 
`DELETE`
 a| 
`/v2.1/fileshares/{id}/`
`snapshot/{name}`
| È possibile eliminare qualsiasi snapshot di una condivisione file in base all'ID della condivisione file e al nome dello snapshot.  a| 
`id`: L'ID della condivisione del file.
`name`: Il nome dello snapshot.

|===

NOTE: Per le condivisioni CIFS, aggiungere un `$` il carattere alla fine del percorso di condivisione lo renderà una condivisione nascosta, ad esempio `pathtomyhiddenshare$`.
