---
sidebar: sidebar 
permalink: seapiref_ontap_clusters.html 
keywords:  
summary:  
---
= Cluster ONTAP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utilizzare i metodi elencati nella tabella seguente per recuperare, creare, modificare ed eliminare i cluster ONTAP.

|===
| Metodo HTTP | Percorso | Descrizione 


| `GET` | `/v2.1/ontapclusters` | Recuperare tutti i cluster ONTAP. 


| `GET` | `/v2.1/ontapclusters/{id}` | Recuperare un cluster ONTAP in base all'ID. 


| `POST` | `/v2.1/ontapclusters` | Creare un nuovo cluster ONTAP. 


| `PUT` | `/v2.1/ontapclusters/{id}` | Aggiornare l'inventario del cluster ONTAP in base all'ID. 


| `DELETE` | `/v2.1/ontapclusters/{id}` | Eliminare un cluster ONTAP. 
|===


== Attributi dei cluster ONTAP

La tabella seguente elenca gli attributi del cluster ONTAP.

|===
| Attributo | Tipo | Descrizione 


| `id` | Stringa | L'identificatore univoco del cluster ONTAP. 


| `name` | Stringa | Il nome del cluster ONTAP. 


| `uuid` | Stringa | UUID (Universal Unique Identifier) del cluster ONTAP. 


| `management_ip` | Stringa | L'indirizzo IPv4 di gestione del cluster ONTAP. 


| `username` | Stringa | Il nome del cluster ONTAP 


| `password` | Stringa | La password del cluster ONTAP 


| `provisioning_state` | Stringa  a| 
Identifica se un cluster è disponibile per le operazioni di provisioning. Le opzioni includono:

* Aprire
* Chiuso




| `data_network_ip_cidr` | Stringa | La notazione CIDR di una subnet. 


| `data_network_default_gateway` | Stringa | L'indirizzo IPV4. 


| `data_network_ports` | –  a| 
Un elenco delle porte della rete dati del cluster ONTAP.

[listing]
----
For example:
[
  {
  "node_name": "dev-ots-per01-01",
  "port_name": "e0c-120",
  "parent_port": "e0c"
  }
]
----


| `intercluster_lifs` | –  a| 
Le LIF del cluster ONTAP.

[listing]
----
For example:
[
  {
  "name": "peer1",
  "node": "aff-01",
  "port": "a0a-103",
  "address": "10.128.113.232",
  "netmask": "255.255.255.0"
  },
{
  "name": "peer2",
  "node": "aff-02",
  "port": "a0a-103",
  "address": "10.128.113.233",
  "netmask": "255.255.255.0"
  }
]
----


| `svm_root_service_level` | Stringa | Il nome del livello di servizio root della SVM (Cluster Storage Virtual Machine) di ONTAP. I valori applicabili sono Standard, Extreme o Premium. Questo livello di servizio viene assegnato per impostazione predefinita a tutte le SVM create nel cluster. Il cluster deve avere un aggregato associato per il livello di servizio indicato. 


| `zone` | Stringa | Il nome della zona. 


| `Subscription_number` | Stringa | L'abbonamento a Zuora. 


| `services_available` | –  a| 
Elenco dei servizi disponibili e relativo stato. Ad esempio:

[listing]
----
{
  "fcp": false,
  "iscsi": true,
  "nas": true
  }
----


| `data_fcp_ports` | –  a| 
Elenco di nodi e porte per cluster ONTAP abilitati per FCP. Ad esempio:

[listing]
----
[  {   "node_name": "aff-01",   "port_name": "0g"  },  {   "node_name": "aff-01",   "port_name": "0h"
  ]
----


| `is_mcc` | Booleano | Indica se il cluster è abilitato o meno per MetroCluster. L'impostazione predefinita è Falso. 


| `mcc_partner_cluster` | Stringa | L'identificatore del cluster partner del cluster corrente in una coppia MetroCluster. Obbligatorio se il cluster è abilitato per MetroCluster. 
|===


== Recuperare tutti i cluster ONTAP

Utilizzare il metodo indicato di seguito per recuperare tutti i cluster ONTAP o un sottoinsieme di cluster ONTAP.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `GET` | `/v2.1/ontapclusters` | Recuperare tutti i cluster ONTAP. | `offset` e. `limit` – vedere link:seapiref_netapp_service_engine_rest_apis.html#pagination>["Impaginazione comune"] 
|===
Attributi del corpo della richiesta richiesti: `none`

*Esempio di corpo della richiesta:*

....
none
....
*Esempio di corpo di risposta:*

....
{
  "status": {
    "user_message": "Okay. Returned 2 records.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 2,
    "total_records": 5,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 3,
    "limit": 2,
    "records": [
      {
        "id": "5c5bb9f16680a7002a5f7450",
        "name": "dev-ots-per01",
        "region": "au-west1",
        "zone": "au-west1-a",
        "uuid": "63053baa-ada4-11ea-b197-005056a4c0ef",
        "management_ip": "10.128.115.173",
        "username": "admin",
        "services_available": {
          "fcp": false,
          "iscsi": true,
          "nas": true
        },
        "provisioning_state": "open",
        "data_network_ports": [
          {
            "node_name": "dev-ots-per01-01",
            "port_name": "e0c-120",
            "parent_port": "e0c"
          }
        ],
        "data_network_ip_cidr": "10.96.120.0/24",
        "data_network_default_gateway": "10.96.120.1",
        "svm_root_service_level": "performance",
        "intercluster_lifs": [
          {
            "name": "dev-ots-per01-01-icl01",
            "node": "dev-ots-per01-01",
            "port": "e0b",
            "address": "10.128.115.144",
            "netmask": "255.255.255.0"
          }
        ],
        "subscription_number": "A-S00003875",
        "created": "2019-02-22T03:38:38.867Z",
        "data_fcp_ports": []
      },
      {
        "id": "5eaf5249f038943eb46b6608",
        "name": "aff",
        "region": "au-east1",
        "zone": "au-east1-b",
        "uuid": "62d649d2-07a1-11e6-9549-00a0985c0dcb",
        "management_ip": "10.128.113.69",
        "username": "admin",
        "services_available": {
          "fcp": true,
          "iscsi": true,
          "nas": true
        },
        "provisioning_state": "open",
        "data_network_ports": [
          {
            "node_name": "aff-01",
            "port_name": "a0a-2000",
            "parent_port": "a0a"
          },
          {
            "node_name": "aff-02",
            "port_name": "a0a-2000",
            "parent_port": "a0a"
          }
        ],
        "data_network_ip_cidr": "10.50.50.0/24",
        "data_network_default_gateway": "10.50.50.1",
        "svm_root_service_level": "premium",
        "intercluster_lifs": [
          {
            "name": "peer1",
            "node": "aff-01",
            "port": "a0a-103",
            "address": "10.128.113.232",
            "netmask": "255.255.255.0"
          },
          {
            "name": "peer2",
            "node": "aff-02",
            "port": "a0a-103",
            "address": "10.128.113.233",
            "netmask": "255.255.255.0"
          }
        ],
        "subscription_number": "A-S00004635",
        "created": "2019-02-22T03:38:38.867Z",
        "data_fcp_ports": [
          {
            "node_name": "aff-01",
            "port_name": "0g"
          },
          {
            "node_name": "aff-01",
            "port_name": "0h"
          },
          {
            "node_name": "aff-02",
            "port_name": "0g"
          },
          {
            "node_name": "aff-02",
            "port_name": "0h"
          }
        ],
        "is_mcc": false,
        "created": "1995-09-07T10:40:52Z"
      }
    ]
  }
}
....


== Recuperare i cluster ONTAP in base all'ID

Utilizzare il metodo elencato di seguito per recuperare i cluster ONTAP in base all'ID.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `GET` | `/v2.1/ontapclusters/{id}` | Recuperare i cluster ONTAP identificati dall'ID. | `id (string)`L'identificatore univoco del cluster ONTAP. 
|===
Attributi del corpo della richiesta richiesti: `none`

*Esempio di corpo della richiesta:*

....
none
....
*Esempio di corpo di risposta:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5c5bb9f16680a7002a5f7450",
        "name": "dev-ots-per01",
        "region": "au-west1",
        "zone": "au-west1-a",
        "uuid": "63053baa-ada4-11ea-b197-005056a4c0ef",
        "management_ip": "10.128.115.173",
        "username": "admin",
        "services_available": {
          "fcp": false,
          "iscsi": true,
          "nas": true
        },
        "provisioning_state": "open",
        "data_network_ports": [
          {
            "node_name": "dev-ots-per01-01",
            "port_name": "e0c-120",
            "parent_port": "e0c"
          }
        ],
        "data_network_ip_cidr": "10.96.120.0/24",
        "data_network_default_gateway": "10.96.120.1",
        "svm_root_service_level": "performance",
        "intercluster_lifs": [
          {
            "name": "dev-ots-per01-01-icl01",
            "node": "dev-ots-per01-01",
            "port": "e0b",
            "address": "10.128.115.144",
            "netmask": "255.255.255.0"
          }
        ],
        "subscription_number": "A-S00003875",
        "created": "2019-02-22T03:38:38.867Z",
        "data_fcp_ports": [],
        "is_mcc": false,
        "created": "1995-09-07T10:40:52Z"
      }
    ]
  }
}
....


== Creare un cluster ONTAP

Utilizzare l'API nella tabella seguente per creare un cluster ONTAP.

I cluster ONTAP vengono sempre creati con il servizio iSCSI attivato. Facoltativamente, è possibile attivare il servizio FCP se supportato dall'infrastruttura.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `POST` | `/v2.1/ontapclusters` | Creare un cluster ONTAP. | Nessuno 
|===
Attributi del corpo della richiesta richiesti: `name`, `uuid, management_ip`, `username`, `password`, `data_network_ip_cidr`, `data_network_default_gateway`, `intercluster_lifs`, `zone`

Se FCP è attivato (utilizzando il `services_available` FCP), i `dATA_fcp_ports `sono obbligatori.

Se `is_mcc` è vero, il `mcc_partner_cluster` è obbligatorio.

*Esempio di corpo della richiesta:*

....
{
  "name": "clustername",
  "uuid": "49b6e08e-513a-11ea-b197-005056a4c0ef",
  "management_ip": "10.128.112.165",
  "username": "admin",
  "password": "ClusterPassword",
  "provisioning_state": "open",
  "data_network_ip_cidr": "10.96.112.0/24",
  "data_network_default_gateway": "10.96.112.1",
  "data_network_ports": [
    {
      "node_name": "clustername-01",
      "port_name": "e0c-112",
      "parent_port": "e0c"
    }
  ],
  "intercluster_lifs": [
    {
      "name": "clustername-01-icl01",
      "node": "clustername-01",
      "port": "e0b",
      "address": "10.128.112.222",
      "netmask": "255.255.255.0"
    }
  ],
  "svm_root_service_level": "extreme",
  "zone": "MyZone",
  "subscription_number": "",
  "services_available": {
    "fcp": false,
    "iscsi": true,
    "nas": true
  },
  "data_fcp_ports": [
  ],
  "is_mcc": false,
}
....
*Esempio di corpo di risposta:*

....
{
    "status": {
        "user_message": "Okay. New resource created.",
        "verbose_message": "",
        "code": 201
    },
    "result": {
        "returned_records": 1,
        "records": [
            {
                "id": "5ef155b8f5591100010a75c5",
                "name": "clustername",
                "region": "MyRegion",
                "zone": "MyZone",
                "uuid": "49b6e08e-513a-11ea-b197-005056a4c0ef",
                "management_ip": "10.128.112.165",
                "username": "admin",
                "services_available": {
                    "fcp": false,
                    "iscsi": true,
                    "nas": true
                },
                "provisioning_state": "open",
                "data_network_ports": [
                    {
                        "node_name": "clustername-01",
                        "port_name": "e0c-112",
                        "parent_port": "e0c"
                    }
                ],
                "data_network_ip_cidr": "10.96.112.0/24",
                "data_network_default_gateway": "10.96.112.1",
                "svm_root_service_level": "extreme",
                "intercluster_lifs": [
                    {
                        "name": "clustername-01-icl01",
                        "node": "clustername-01",
                        "port": "e0b",
                        "address": "10.128.112.222",
                        "netmask": "255.255.255.0"
                    }
                ],
                "subscription_number": "",
                "created": "2020-06-23T01:07:04.563Z",
                "data_fcp_ports": [],
                "is_mcc": false,
                "mcc_partner_cluster": "5d2fb0fb4f47df00015274e3",
                "created": "1995-09-07T10:40:52Z"
            }
        ]
    }
}
....


== Modificare il cluster ONTAP

Utilizzare il metodo indicato di seguito per modificare il cluster ONTAP.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `PUT` | `/v2.1/ontapclusters/{id}` | Modificare i dettagli del cluster ONTAP identificato dall'ID. | `id (string)`L'identificatore univoco del cluster ONTAP. 
|===
Attributi del corpo della richiesta richiesti: `none`

*Esempio di corpo della richiesta:*

....
{
  "name": "clustername",
  "uuid": "49b6e08e-513a-11ea-b197-005056a4c0ef",
  "management_ip": "10.128.112.165",
  "username": "admin",
  "password": "ClusterPassword",
  "provisioning_state": "open",
  "data_network_ip_cidr": "10.96.112.0/24",
  "data_network_default_gateway": "10.96.112.1",
  "data_network_ports": [
    {
      "node_name": "dev-ots-syd01-01",
      "port_name": "e0c-112",
      "parent_port": "e0c"
    }
  ],
  "intercluster_lifs": [
    {
      "name": "dev-ots-syd01-01-icl01",
      "node": "dev-ots-syd01-01",
      "port": "e0b",
      "address": "10.128.112.222",
      "netmask": "255.255.255.0"
    }
  ],
  "svm_root_service_level": "standard",
  "zone": "MyZone",
  "subscription_number": "",
  "services_available": {
    "fcp": false,
    "iscsi": true,
    "nas": false
  },
  "data_fcp_ports": [
  ]
}
....
*Esempio di corpo di risposta:*

....
{
    "status": {
        "user_message": "Okay. Accepted for processing.",
        "verbose_message": "",
        "code": 202
    },
    "result": {
        "returned_records": 1,
        "records": [
            {
                "id": "5ef155b8f5591100010a75c5",
                "name": "clustername",
                "region": "MyRegion",
                "zone": "MyZone",
                "uuid": "49b6e08e-513a-11ea-b197-005056a4c0ef",
                "management_ip": "10.128.112.165",
                "username": "admin",
                "services_available": {
                    "fcp": false,
                    "iscsi": true,
                    "nas": true
                },
                "provisioning_state": "open",
                "data_network_ports": [
                    {
                        "node_name": "dev-ots-syd01-01",
                        "port_name": "e0c-112",
                        "parent_port": "e0c"
                    }
                ],
                "data_network_ip_cidr": "10.96.112.0/24",
                "data_network_default_gateway": "10.96.112.1",
                "svm_root_service_level": "standard",
                "intercluster_lifs": [
                    {
                        "name": "dev-ots-syd01-01-icl01",
                        "node": "dev-ots-syd01-01",
                        "port": "e0b",
                        "address": "10.128.112.222",
                        "netmask": "255.255.255.0"
                    }
                ],
                "subscription_number": "",
                "created": "2020-06-23T01:07:04.563Z",
                "data_fcp_ports": [],
                "is_mcc": false,
                "mcc_partner_cluster": "5d2fb0fb4f47df00015274e3",
                "created": "1995-09-07T10:40:52Z"
            }
        ]
    }
}
....


== Eliminare un cluster ONTAP

Utilizzare il metodo elencato nella tabella seguente per eliminare un cluster ONTAP.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `DELETE` | `/v2.1/ontapclusters/{id}` | Eliminare il cluster ONTAP identificato dall'ID. | `id (string)`L'identificatore univoco del cluster ONTAP. 
|===
Attributi del corpo della richiesta richiesti: `none`

*Esempio di corpo della richiesta:*

....
none
....
*Esempio di corpo di risposta:*

....
No content for succesful delete
....