---
sidebar: sidebar 
permalink: seapiref_subnets_apis.html 
keywords: netapp, keystone, subnets, networks, apis 
summary: API di rete Keystone 
---
= Definire le configurazioni di rete con le API delle subnet
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile utilizzare le API delle sottoreti per visualizzare e creare sottoreti per il proprio subtenant e la propria zona. È possibile utilizzarli per definire la configurazione di rete.

[cols="1,1,3,2"]
|===
| Verbo HTTP | Percorso | Descrizione | Parametri obbligatori/corpo della richiesta 


 a| 
`GET`
 a| 
`/v2.1/tenants/{tenant_id}/`
`zones/{zone_name}/subnets`
| È possibile recuperare tutti gli oggetti di subnet di un tenant e di una zona. Recupera i dettagli della subnet, ad esempio VLAN, subtenant, zona, route, e tag.  a| 
`tenant_id`: L'ID del tenant.
`zone_name`: Il nome della zona.
`offset`: Il numero di elementi da saltare prima di iniziare a raccogliere il set di risultati.
`limit`: Il numero di elementi da restituire.



 a| 
`GET`
 a| 
`/v2.1/tenants/{tenant_id}/`
`zones/{zone_name}/subnets/`
`{id}`
| È possibile recuperare i dettagli di un oggetto subnet specifico creato per un tenant e una zona. Recupera i dettagli della subnet, ad esempio VLAN, subtenant, zona, route, E i tag in base all'ID inserito.  a| 
`tenant_id`: L'ID del tenant.
`zone_name`: Il nome della zona.
`id`: L'ID della subnet.



 a| 
`POST`
 a| 
`/v2.1/tenants/{tenant_id}/`
`zones/{zone_name}/subnets`
| È possibile creare un oggetto subnet per un tenant e una zona specifici. Aggiungere i valori nel corpo della richiesta per creare un oggetto subtenant con i parametri specificati, ad esempio nome, VLAN, CIDR, ID subtenant, percorsi e tag.  a| 
`tenant_id`: L'ID del tenant.
`zone_name`: Il nome della zona.``
{
  "name": "string",
  "vlan": "1000",
  "cidr": "10.0.0.0/24",
  "subtenant_id": "5d2fb0fb4f47df00015274e3",
  "routes": [
    {
      "destination": "10.0.0.0/24",
      "gateway": "10.0.0.1",
      "metric": "20"
    }
  ],
  "tags": {
    "key1": "Value 1",
    "key2": "Value 2",
    "keyN": "Value N"
  }
}
``



 a| 
`POST`
 a| 
`/v2.1/tenants/{tenant_id}/`
`zones/{zone_name}/subnets/`
`{id}/tags`
| È possibile creare o sostituire tag per un oggetto subnet per il tenant. Aggiungere l'ID dell'oggetto subnet e i valori per i tag nel formato "coppia chiave:valore" nel corpo della richiesta.  a| 
`tenant_id`: L'ID del tenant.
`zone_name`: Il nome della zona.
`id`: L'ID dell'oggetto di backup.``
{
  "key1": "<Tag 1>",
  "key2": "<Tag 2>",
  "keyN": "<Tag N>"
}
``

|===