---
sidebar: sidebar 
permalink: seapiref_object_storage_apis.html 
keywords: netapp, keystone, object, storage, apis, 
summary: API di storage a oggetti Keystone 
---
= API dello storage a oggetti
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Questa sezione fornisce le API per gestire lo storage a oggetti, gli utenti dello storage a oggetti e il gruppo di storage a oggetti.

Il flusso di lavoro dello storage a oggetti include le seguenti attività:

* Creare un account di storage a oggetti.
* Creare un gruppo di storage a oggetti.
* Creare un utente dello storage a oggetti.
* Creare una chiave S3 per l'utente.




== Gruppi di storage a oggetti

Utilizzare i metodi elencati nella tabella seguente per recuperare, creare o modificare i gruppi di storage a oggetti.

|===
| Metodo HTTP | Percorso | Descrizione 


| `GET` | `/v2.1/objectiam/groups` | Recuperare i gruppi di storage a oggetti. 


| `GET` | `/v2.1/objectiam/groups/{id}` | Recuperare un gruppo di storage a oggetti per ID. 


| `POST` | `/v2.1/objectiam/groups` | Creare un gruppo di gestione dell'accesso all'identità dello storage a oggetti. 


| `PUT` | `/v2.1/objectiam/groups/{id}` | Modificare un gruppo di storage a oggetti identificato dall'ID. 


| `DELETE` | `/v2.1/objectiam/groups/{id}` | Eliminare un gruppo di storage a oggetti identificato dall'ID. 
|===


=== Attributi del gruppo di storage a oggetti

Nella tabella seguente sono elencati gli attributi di storage degli oggetti.

|===
| Attributo | Tipo | Descrizione 


| `id` | Stringa | Identificatore univoco del gruppo di storage a oggetti. 


| `name` | Stringa | Il nome del gruppo di storage a oggetti. 


| `subtenant` | Stringa | Il nome del subtenant a cui appartiene il gruppo. 


| `subtenant_id` | Stringa | Identificativo del sottenant a cui appartiene il gruppo. 


| `tenant` | Stringa | Il nome del tenant a cui appartiene il gruppo. 


| `tenant_id` | Stringa | Identificativo del tenant a cui appartiene il gruppo. 


| `s3_policy` |   a| 
Policy S3 ad esempio:

[listing]
----
"s3_policy": {
    "Statement": [
      {
        "Effect": "Allow",
        "Action": "s3:*",
        "Resource": "arn:aws:s3:::*"
      }
    ]
  }
----
|===


=== Recuperare i gruppi di storage a oggetti

Utilizzare il metodo elencato nella tabella seguente per recuperare tutti i gruppi di storage a oggetti o un sottoinsieme di gruppi di storage a oggetti. Specificare un `subtenant_id` restituisce solo i gruppi di storage a oggetti appartenenti a quel sottenant.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `GET` | `/v2.1/objectiam/groups` | Recuperare tutti i gruppi di storage a oggetti. Se si desidera, specificare un ID del sottotenant per recuperare solo i gruppi di storage a oggetti associati al sottenant. | `subtenant_id (string)`: L'ID del sottotenant associato agli utenti/gruppi IAM (Identity and Access Management).
`offset` e. `limit`– vedere link:seapiref_netapp_service_engine_rest_apis.html#pagination>["Impaginazione comune"] 
|===
Attributi del corpo della richiesta richiesti: `none`

*Esempio di corpo della richiesta:*

....
none
....
*Esempio di corpo di risposta:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "total_records": 1,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 0,
    "limit": 20,
    "records": [
      {
        "id": "5eb1eff8bc5c0300011c989c",
        "name": "MyGroup",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant",
        "subtenant_id": "5e7c3af8aab46c00014ce878",
        "subtenant": "MySubtenant",
        "s3_policy": {
          "Statement": [
            {
              "Action": [
                "s3:*"
              ],
              "Effect": "Allow",
              "Resource": "arn:aws:s3:::*"
            }
          ]
        }
      }
    ]

....


=== Recuperare un gruppo di storage a oggetti per ID

Utilizzare il metodo elencato nella tabella seguente per recuperare un gruppo di storage a oggetti in base all'ID.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `GET` | `/v2.1/objectiam/groups/{id}` | Recuperare un gruppo di storage a oggetti per ID. | `id (string)`L'identificatore univoco del gruppo di storage a oggetti. 
|===
Attributi del corpo della richiesta richiesti: `none`

*Esempio di corpo della richiesta:*

....
none
....
*Esempio di corpo di risposta:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5eb1eff8bc5c0300011c989c",
        "name": "MyGroup",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant",
        "subtenant_id": "5e7c3af8aab46c00014ce878",
        "subtenant": "MySubtenant",
        "s3_policy": {
          "Statement": [
            {
              "Action": [
                "s3:*"
              ],
              "Effect": "Allow",
              "Resource": "arn:aws:s3:::*"
            }
          ]
        }
      }
    ]
  }
....


=== Creare un gruppo di storage a oggetti

Per creare un gruppo di storage a oggetti, utilizzare il metodo descritto di seguito.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `POST` | `/v2.1/objectiam/groups/` | Creare un nuovo servizio di gruppo di storage a oggetti per ospitare gli utenti dello storage a oggetti. | Nessuno 
|===
Attributi del corpo della richiesta richiesti: `name`, `subtenant_id`, `s3Policy`

*Esempio di corpo della richiesta:*

....
{
  "name": "MyNewGroup",
  "subtenant_id": "5e7c3af8aab46c00014ce878",
  "s3_policy": {
    "Statement": [
      {
        "Effect": "Allow",
        "Action": "s3:*",
        "Resource": "arn:aws:s3:::*"
      }
    ]
  }
}
....
*Esempio di corpo di risposta:*

....
{
  "status": {
    "user_message": "Okay. Accepted for processing.",
    "verbose_message": "",
    "code": 202
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ed5fa312c356a0001a73841",
        "action": "create",
        "job_summary": "Create request is successfully submitted",
        "created": "2020-06-02T07:05:21.130260774Z",
        "updated": "2020-06-02T07:05:21.130260774Z",
        "object_id": "5ed5fa312c356a0001a73840",
        "object_type": "sg_groups",
        "object_name": "MyNewGroup",
        "status": "pending",
        "status_detail": "",
        "last_error": "",
        "user_id": "5ec626c0f038943eb46b0af1",
        "job_tasks": null
      }
    ]
  }
}
....


=== Modificare un gruppo di storage a oggetti

Utilizzare il metodo elencato nella tabella seguente per modificare un gruppo di storage a oggetti.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `PUT` | `/v2.1/objectiam/groups/{id}` | Modificare un gruppo di storage a oggetti. | `id (string)`L'identificatore univoco del gruppo di storage a oggetti. 
|===
Attributi del corpo della richiesta richiesti: `name`, `subtenant_id`, `s3Policy`

*Esempio di corpo della richiesta:*

....
{
  "s3_policy": {
    "Statement": [
        {
        "Action": [
            "s3:ListAllMyBuckets",
            "s3:ListBucket",
            "s3:ListBucketVersions",
            "s3:GetObject",
            "s3:GetObjectTagging",
            "s3:GetObjectVersion",
            "s3:GetObjectVersionTagging"
        ],
        "Effect": "Allow",
        "Resource": "arn:aws:s3:::*"
        }
    ]
  }
}
....
*Esempio di corpo di risposta:*

....
{
  "status": {
    "user_message": "Okay. Accepted for processing.",
    "verbose_message": "",
    "code": 202
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ed5fe822c356a0001a73859",
        "action": "update",
        "job_summary": "Update request is successfully submitted",
        "created": "2020-06-02T07:23:46.43550235Z",
        "updated": "2020-06-02T07:23:46.43550235Z",
        "object_id": "5ed5fa312c356a0001a73840",
        "object_type": "sg_groups",
        "object_name": "MyNewGroup",
        "status": "pending",
        "status_detail": "",
        "last_error": "",
        "user_id": "5ec626c0f038943eb46b0af1",
        "job_tasks": null
      }
    ]
  }
}
....


=== Eliminare un gruppo di storage a oggetti in base all'ID

Utilizzare il metodo elencato nella tabella seguente per eliminare un gruppo di storage a oggetti in base all'ID.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `Delete` | `/v2.1/objectiam/groups/{id}` | Eliminare un gruppo di storage a oggetti in base all'ID. | `id (string)`L'identificatore univoco del gruppo di storage a oggetti. 
|===
Attributi del corpo della richiesta richiesti: `none`

*Esempio di corpo della richiesta:*

....
none
....
*Esempio di corpo di risposta:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5eb1eff8bc5c0300011c989c",
        "name": "MyGroup",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant",
        "subtenant_id": "5e7c3af8aab46c00014ce878",
        "subtenant": "MySubtenant",
        "s3_policy": {
          "Statement": [
            {
              "Action": [
                "s3:*"
              ],
              "Effect": "Allow",
              "Resource": "arn:aws:s3:::*"
            }
          ]
        }
      }
    ]
  }
....


== Utenti dello storage a oggetti

Utilizzare i metodi elencati nella seguente tabella per eseguire le seguenti operazioni:

* Recuperare, creare o modificare gli utenti dello storage a oggetti.
* Creare chiavi S3, recuperare le chiavi S3 per un utente o recuperare le chiavi in base all'ID della chiave.


|===
| Metodo HTTP | Percorso | Descrizione 


| `GET` | `/v2.1/objectiam/users` | Recuperare gli utenti dello storage a oggetti. 


| `GET` | `/v2.1/objectiam/users/{id}` | Recuperare un utente dello storage a oggetti in base all'ID. 


| `POST` | `/v2.1/objectiam/users` | Creare un utente dello storage a oggetti. 


| `PUT` | `/v2.1/objectiam/users/{id}` | Modificare un utente dello storage a oggetti identificato dall'ID. 


| `DELETE` | `/v2.1/objectiam/users/{id}` | Eliminare un utente dello storage a oggetti in base all'ID. 


| `GET` | `/v2.1/objectiam/users/{user_id}/s3keys` | Ottenere tutte le chiavi S3 mappate a un utente. 


| `POST` | `/v2.1/objectiam/users/{user_id}/s3keys` | Creare chiavi S3. 


| `GET` | `/v2.1/objectiam/users/{user_id}/s3keys/{key_id}` | Ottieni le chiavi S3 in base all'ID della chiave. 


| `DELETE` | `/v2.1/objectiam/users/{user_id}/s3keys/{key_id}` | Eliminare le chiavi S3 in base all'ID della chiave. 
|===


=== Attributi utente dello storage a oggetti

Nella tabella seguente sono elencati gli attributi utente dello storage a oggetti.

|===
| Attributo | Tipo | Descrizione 


| `id` | Stringa | Identificatore univoco dell'utente dello storage a oggetti. 


| `display_name` | Stringa | Il nome visualizzato dell'utente. 


| `subtenant` | Stringa | Il nome del subtenant a cui appartiene l'utente. 


| `subtenant_id` | Stringa | Identificativo del sottostruttant a cui appartiene l'utente. 


| `tenant` | Stringa | Il nome del tenant a cui appartiene l'utente. 


| `tenant_id` | Stringa | Identificativo del tenant a cui appartiene l'utente. 


| `objectiam_user_urn` | Stringa | L'URN. 


| `sg_group_membership` | Stringa | Membri del gruppo NetApp StorageGRID. Ad esempio: "sg_Group_Membership": [ "5d2fb0fb4f47df00015274e3" ] 
|===


=== Recuperare gli utenti dello storage a oggetti

Utilizzare il metodo elencato nella tabella seguente per recuperare tutti gli utenti dello storage a oggetti o un sottoinsieme di utenti dello storage a oggetti. Specificare un `subtenant_id` restituisce solo i gruppi di storage a oggetti appartenenti a quel sottenant.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `GET` | `/v2.1/objectiam/users` | Recuperare tutti gli utenti dello storage a oggetti. | `subtenant_id (string)`: L'ID del sottotenant associato agli utenti/gruppi IAM.
`offset` e. `limit` – vedere link:seapiref_netapp_service_engine_rest_apis.html#pagination>["Impaginazione comune"] 
|===
Attributi del corpo della richiesta richiesti: `none`

*Esempio di corpo della richiesta:*

....
none
....
*Esempio di corpo di risposta:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "total_records": 1,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 0,
    "limit": 20,
    "records": [
      {
        "id": "5eb2212d1cbe3b000134762e",
        "display_name": "MyUser",
        "subtenant": "MySubtenant",
        "subtenant_id": "5e7c3af8aab46c00014ce878",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant",
        "objectiam_user_urn": "urn:sgws:identity::96465636379595351967:user/myuser",
        "sg_group_membership": [
          "5eb1eff8bc5c0300011c989c"
        ]
      }
    ]
  }
}
....


=== Recuperare un utente dello storage a oggetti in base all'ID

Utilizzare il metodo elencato nella tabella seguente per recuperare un utilizzo dello storage a oggetti per ID.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `GET` | `/v2.1/objectiam/users{id}` | Recuperare un utente dello storage a oggetti in base all'ID. | `id`: L'ID del centro di costo dello storage a oggetti. 
|===
Attributi del corpo della richiesta richiesti: `none`

*Esempio di corpo della richiesta:*

....
none
....
*Esempio di corpo di risposta:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5eb2212d1cbe3b000134762e",
        "display_name": "MyUser",
        "subtenant": "MySubtenant",
        "subtenant_id": "5e7c3af8aab46c00014ce878",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant",
        "objectiam_user_urn": "urn:sgws:identity::96465636379595351967:user/myuser",
        "sg_group_membership": [
          "5eb1eff8bc5c0300011c989c"
        ]
      }
    ]
  }
}
....


=== Creare un utente dello storage a oggetti

Utilizzare il metodo elencato nella tabella seguente per creare un utente dello storage a oggetti.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `POST` | `/v2.1/objectiam/users` | Creare un nuovo utente di storage a oggetti. | Nessuno 
|===
Attributi del corpo della richiesta richiesti: `display_name`, `subtenant_id`, `sg_group_membership`

*Esempio di corpo della richiesta:*

....
{
  "display_name": "MyUserName",
  "subtenant_id": "5e7c3af8aab46c00014ce878",
  "sg_group_membership": [
    "5ed5fa312c356a0001a73840"
  ]
}
....
*Esempio di corpo di risposta:*

....
{
  "status": {
    "user_message": "Okay. Accepted for processing.",
    "verbose_message": "",
    "code": 202
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ed603712c356a0001a7386c",
        "action": "create",
        "job_summary": "Activate request is successfully submitted",
        "created": "2020-06-02T07:44:49.647815816Z",
        "updated": "2020-06-02T07:44:49.647815816Z",
        "object_id": "5ed603712c356a0001a7386d",
        "object_type": "sg_users",
        "object_name": "MyUserName",
        "status": "pending",
        "status_detail": "",
        "last_error": "",
        "user_id": "5ec626c0f038943eb46b0af1",
        "job_tasks": null
      }
    ]
  }
}
....


=== Modificare un utente dello storage a oggetti

Utilizzare il metodo elencato nella tabella seguente per modificare un utente dello storage a oggetti.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `PUT` | `/v2.1/objectiam/users/{id}` | Modificare un utente dello storage a oggetti identificato dall'ID. | `id`: L'ID utente dello storage a oggetti. 
|===
Attributi del corpo della richiesta richiesti: `display_name`, `subtenant_id`, `sg_group_membership`

*Esempio di corpo della richiesta:*

....
{
  "display_name": "MyModifiedObjectStorageUser",
  "subtenant_id": "5e57a465896bd80001dd4961",
  "sg_group_membership": [
    "5e60754f9b64790001fe937b"
  ]
}
....
*Esempio di corpo di risposta:*

....
{
  "status": {
    "user_message": "Okay. Accepted for processing.",
    "verbose_message": "",
    "code": 202
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ed604002c356a0001a73880",
        "action": "update",
        "job_summary": "Update request is successfully submitted",
        "created": "2020-06-02T07:47:12.205889873Z",
        "updated": "2020-06-02T07:47:12.205889873Z",
        "object_id": "5ed603712c356a0001a7386d",
        "object_type": "sg_users",
        "object_name": "MyUserName",
        "status": "pending",
        "status_detail": "",
        "last_error": "",
        "user_id": "5ec626c0f038943eb46b0af1",
        "job_tasks": null
      }
    ]
  }
}
....


=== Mappare tutte le chiavi S3 a un utente dello storage a oggetti

Utilizzare il metodo elencato nella tabella seguente per associare tutte le chiavi S3 a un utente dello storage a oggetti.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `GET` | `/v2.1/objectiam/users/{user_id}/s3keys` | Creare una chiave S3 per un utente dello storage a oggetti. | `user_id (string)`L'identificativo dell'utente dello storage a oggetti. 
|===
Attributi del corpo della richiesta richiesti: `none`

*Esempio di corpo della richiesta:*

....
none
....
*Esempio di corpo di risposta:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5e66de2509a74c0001b895e7",
        "display_name": "****************HNDE",
        "subtenant_id": "5e57a465896bd80001dd4961",
        "subtenant": "BProject",
        "objectiam_user_id": "5e66c77809a74c0001b89598",
        "objectiam_user": "MyNewObjectStorageUser",
        "objectiam_user_urn": "urn:sgws:identity::09936502886898621050:user/mynewobjectstorageuser",
        "expires": "2020-04-07T10:40:52Z"
      }
    ]
....


=== Creare una chiave S3 per un utente dello storage a oggetti

Utilizzare il metodo elencato di seguito per creare una chiave S3 per un utente dello storage a oggetti.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `POST` | `/v2.1/objectiam/users/{user_id}/s3keys` | Creare una chiave S3 per un utente dello storage a oggetti. | `user_id (string)`L'identificativo dell'utente dello storage a oggetti. 
|===
Attributi del corpo della richiesta richiesti: `expires` (stringa)


NOTE: La data e l'ora di scadenza della chiave sono impostate in UTC e devono essere impostate in futuro.

*Esempio di corpo della richiesta:*

....
{
  "expires": "2020-04-07T10:40:52Z"
}
....
*Esempio di corpo di risposta:*

....
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "id": "5e66de2509a74c0001b895e7",
        "display_name": "****************HNDE",
        "subtenant_id": "5e57a465896bd80001dd4961",
        "subtenant": "BProject",
        "objectiam_user_id": "5e66c77809a74c0001b89598",
        "objectiam_user": "MyNewObjectStorageUser",
        "objectiam_user_urn": "urn:sgws:identity::09936502886898621050:user/mynewobjectstorageuser",
        "expires": "2020-04-07T10:40:52Z",
        "access_key": "PL86KPEBN6XT4T7UHNDE",
        "secret_key": "FlD/YWAM7JMr9gG8pumU8dzvcTLMzLYtUe2lNzcA"
      }
    ]
  }
}
....


=== Ottenere le chiavi S3 per un utente dello storage a oggetti in base all'ID della chiave

Utilizzare il metodo elencato nella tabella seguente per ottenere le chiavi S3 per un utente dello storage a oggetti in base all'ID della chiave.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `GET` | `/v2.1/objectiam/users/{user_id}/s3keys/{key_id}` | Ottieni le chiavi S3 in base all'ID della chiave.  a| 
* `user_id (string)`: L'ID utente dello storage a oggetti. Ad esempio: 5e66c77809a74c0001b89598
* `key_id (string)`: Chiave S3 ad esempio: 5e66de2509a74c0001b895e7


|===
Attributi del corpo della richiesta richiesti: `none`

*Esempio di corpo della richiesta:*

....
none
....
*Esempio di corpo di risposta:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ecc7bb9b5d2730001f798fb",
        "display_name": "****************XCXD",
        "subtenant_id": "5e7c3af8aab46c00014ce878",
        "subtenant": "MySubtenant",
        "objectiam_user_id": "5eb2212d1cbe3b000134762e",
        "objectiam_user": "MyUser",
        "objectiam_user_urn": "urn:sgws:identity::96465636379595351967:user/myuser",
        "expires": "2020-05-27T00:00:00Z"
      }
    ]
  }
}
....


=== Eliminare una chiave S3 in base all'ID della chiave

Utilizzare il metodo riportato nella tabella seguente per eliminare una chiave S3 in base all'ID della chiave.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `Delete` | `/v2.1/objectiam/users/{user_id}/s3keys/{key_id}` | Eliminare la chiave S3 in base all'ID della chiave.  a| 
* `user_id (string)`: L'ID utente dello storage a oggetti. Ad esempio: 5e66c77809a74c0001b89598
* `key_id (string)`: Chiave S3 ad esempio: 5e66de2509a74c0001b895e7


|===
Attributi del corpo della richiesta richiesti: `none`

*Esempio di corpo della richiesta:*

....
none
....
*Esempio di corpo di risposta:*

....
No content to return for succesful execution
....


== Account di storage a oggetti

Utilizzare i metodi elencati nella seguente tabella per eseguire le seguenti operazioni:

* Recuperare, attivare o modificare gli account di storage a oggetti.
* Creare bucket S3.


|===
| Metodo HTTP | Percorso | Descrizione 


| `GET` | `/v2.1/objectstorage/accounts` | Recuperare gli account di storage a oggetti. 


| `GET` | `/v2.1/objectstorage/accounts/{id}` | Recuperare un account di storage a oggetti in base all'ID. 


| `POST` | `/v2.1/objectstorage/accounts` | Creare un account di storage a oggetti. 


| `PUT` | `/v2.1/objectstorage/accounts/{id}` | Modificare un account di storage a oggetti identificato dall'ID. 


| `DELETE` | `/v2.1/objectstorage/accounts/{id}` | Modificare un account di storage a oggetti identificato dall'ID. 


| `GET` | `/v2.1/objectstorage/buckets` | Ottieni bucket S3. 


| `POST` | `/v2.1/objectstorage/buckets` | Creare bucket S3. 
|===


=== Attributi dell'account di storage a oggetti

Nella tabella seguente sono elencati gli attributi dell'account di storage a oggetti.

|===
| Attributo | Tipo | Descrizione 


| `id` | Stringa | L'identificatore univoco dell'utente dello storage a oggetti. 


| `subtenant_id` | Stringa | L'identificativo dell'istanza di un oggetto subtenant. 


| `quota_gb` | Intero | Le dimensioni della condivisione o del disco. 
|===


=== Recuperare tutti gli account di storage a oggetti

Utilizzare il metodo elencato nella tabella seguente per recuperare tutti gli account di storage a oggetti o un sottoinsieme di account di storage a oggetti.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `GET` | `/v2.1/objectstorage/accounts` | Recuperare tutti gli utenti dello storage a oggetti. | `offset` e. `limit`– . vedere link:seapiref_netapp_service_engine_rest_apis.html#pagination>["Impaginazione comune"] 
|===
Attributi del corpo della richiesta richiesti: `none`

*Esempio di corpo della richiesta:*

....
none
....
*Esempio di corpo di risposta*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "total_records": 19,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 3,
    "limit": 1,
    "records": [
      {
        "id": "5ec6119e6344d000014cdc41",
        "name": "MyTenant - MySubtenant",
        "subtenant": " MySubtenant",
        "subtenant_id": "5ea8c5e083a9f80001b9d705",
        "tenant": "E- MyTenant",
        "tenant_id": "5d914499869caefed0f39eee",
        "sg_account_id": "29420999312809208626",
        "quota_gb": 100,
        "sg_instance_name": "NSE StorageGRID Dev1",
        "sg_instance_id": "5e3ba2840271823644cb8ab6"
      }
    ]
  }
}
....


=== Recuperare un account di storage a oggetti in base all'ID

Utilizzare il metodo elencato nella tabella seguente per recuperare un account di storage a oggetti in base all'ID.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `GET` | `/v2.1/objectstorage/accounts/{id}` | Recuperare un account di storage a oggetti in base all'ID. | `id`: L'ID del centro di costo dello storage a oggetti. 
|===
Attributi del corpo della richiesta richiesti: `none`

*Esempio di corpo della richiesta:*

....
none
....
*Esempio di corpo di risposta:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ec6119e6344d000014cdc41",
        "name": "MyTenant - MySubtennant",
        "subtenant": " MySubtennant",
        "subtenant_id": "5ea8c5e083a9f80001b9d705",
        "tenant": " MyTenant",
        "tenant_id": "5d914499869caefed0f39eee",
        "sg_account_id": "29420999312809208626",
        "quota_gb": 100,
        "sg_instance_name": "NSE StorageGRID Dev1",
        "sg_instance_id": "5e3ba2840271823644cb8ab6"
      }
    ]
  }
....


=== Attivare un account di storage a oggetti

Utilizzare il metodo elencato nella tabella seguente per attivare un account di storage a oggetti.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `POST` | `/v2.1/objectstorage/accounts` | Attivare un servizio di storage a oggetti. | Nessuno 
|===
Attributi del corpo della richiesta richiesti: `subtenant_id, quota_gb`

*Esempio di corpo della richiesta:*

....
{
  "subtenant_id": "5ecefbbef418b40001f20bd6",
  "quota_gb": 20
}
....
*Esempio di corpo di risposta:*

....
{
  "status": {
    "user_message": "Okay. Accepted for processing.",
    "verbose_message": "",
    "code": 202
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ed608542c356a0001a73893",
        "action": "create",
        "job_summary": "Activate request for Sub Tenant MyNewSubtenant is successfully submitted",
        "created": "2020-06-02T08:05:40.017362022Z",
        "updated": "2020-06-02T08:05:40.017362022Z",
        "object_id": "5ed608542c356a0001a73894",
        "object_type": "sg_accounts",
        "object_name": "MyTenant - MyNewSubtenant",
        "status": "pending",
        "status_detail": "",
        "last_error": "",
        "user_id": "5ec626c0f038943eb46b0af1",
        "job_tasks": null
      }
    ]
  }
}
....


=== Modificare un account di storage a oggetti

Utilizzare il metodo elencato nella tabella seguente per modificare un account di storage a oggetti.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `PUT` | `/v2.1/objectstorage/accounts/{id}` | Modificare un servizio di storage a oggetti (ad esempio, modificare la quota). | `id (string)`: L'ID del centro di costo dello storage a oggetti. 
|===
Attributi del corpo della richiesta richiesti: `name`, `subtenant_id`, `quota_gb`

*Esempio di corpo della richiesta:*

....
{
  "name": "MyTenant - MyNewSubtenant",
  "subtenant_id": "5ecefbbef418b40001f20bd6",
  "quota_gb": 30
}
....
*Esempio di corpo di risposta:*

....
{
  "status": {
    "user_message": "Okay. Accepted for processing.",
    "verbose_message": "",
    "code": 202
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ed609162c356a0001a73899",
        "action": "update",
        "job_summary": "Update request is successfully submitted",
        "created": "2020-06-02T08:08:54.841652098Z",
        "updated": "2020-06-02T08:08:54.841652098Z",
        "object_id": "5ed608542c356a0001a73894",
        "object_type": "sg_accounts",
        "object_name": "MyTenant - MyNewSubtenant",
        "status": "pending",
        "status_detail": "",
        "last_error": "",
        "user_id": "5ec626c0f038943eb46b0af1",
        "job_tasks": null
      }
    ]
  }
}
....


=== Eliminare un account di storage a oggetti

Prima di poter eliminare un account di storage a oggetti, è necessario eliminare tutti i gruppi, gli utenti e i bucket associati. Utilizzare il metodo elencato nella tabella seguente per eliminare un account di storage a oggetti.


NOTE: Utilizzare l'utility S3 compatibile per eliminare i bucket. Non è possibile eliminare i bucket da NetApp Service Engine.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `Delete` | `/v2.1/objectstorage/accounts/{id}` | Eliminare un account di storage a oggetti. | `id (string)`: L'ID del centro di costo dello storage a oggetti. 
|===
Attributi del corpo della richiesta richiesti: `none`

*Esempio di corpo della richiesta:*

....
{
  "name": "MyTenant - MyNewSubtenant",
  "subtenant_id": "5ecefbbef418b40001f20bd6",
  "quota_gb": 30
}
....
*Esempio di corpo di risposta:*

....
{
  "status": {
    "user_message": "string",
    "verbose_message": "string",
    "code": "string"
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5d2fb0fb4f47df00015274e3",
        "action": "string",
        "object_id": "5d2fb0fb4f47df00015274e3",
        "object_type": "string",
        "status": "string",
        "status_detail": "string",
        "last_error": "string",
        "user_id": "5d2fb0fb4f47df00015274e3",
        "link": "string"
      }
    ]
  }
}
....


== Bucket di storage a oggetti

Utilizzare le API della tabella seguente per creare e recuperare i bucket di storage a oggetti.

|===
| Metodo HTTP | Percorso | Descrizione 


| `GET` | `/v2.1/objectstorage/buckets` | Recuperare i bucket di storage a oggetti. 


| `POST` | `/v2.1/objectstorage/buckets` | Creare un bucket di storage a oggetti. 
|===


=== Attributi del bucket di storage a oggetti

La tabella seguente elenca gli attributi del bucket di storage a oggetti.

|===
| Attributo | Tipo | Descrizione 


| `id` | Stringa | Identificatore univoco dell'utente dello storage a oggetti. 


| `Name` | Stringa | Il nome del bucket. 


| `subtenant_id` | Stringa | L'identificativo del subtenant a cui appartiene il bucket. 
|===


=== Recuperare i bucket S3

Utilizzare il metodo elencato nella tabella seguente per recuperare i bucket S3.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `GET` | `/v2.1/objectstorage/buckets` | Recuperare i bucket S3. | `Subtenant_id`: Il subtenant proprietario del bucket. 
|===
Attributi del corpo della richiesta richiesti: `none`

*Esempio di corpo della richiesta:*

....
none
....
*Esempio di corpo di risposta:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "creationTime": "2020-06-02T08:13:25.695Z",
        "name": "mybucket"
      }
    ]
  }
}
....


=== Creare bucket S3

Utilizzare il metodo elencato nella tabella seguente per creare un bucket S3.


NOTE: Prima di poter creare un bucket, deve esistere un account di storage a oggetti per il sottenant.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `POST` | `/v2.1/objectstorage/buckets` | Creare un bucket S3. | Nessuno 
|===
Attributi del corpo della richiesta richiesti:

* `name` (Stringa): Nome del bucket S3 (solo caratteri minuscoli o numerici)
* `subtenant_id` (String): ID del subtenant a cui appartiene il bucket S3


*Esempio di corpo della richiesta:*

....
{
  "name": "mybucket",
  "subtenant_id": "5ecefbbef418b40001f20bd6"
}
....
*Esempio di corpo di risposta:*

....
{
  "status": {
    "user_message": "Okay. Accepted for processing.",
    "verbose_message": "",
    "code": 202
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ed60a232c356a0001a7389e",
        "action": "create",
        "job_summary": "Create request is successfully submitted",
        "created": "2020-06-02T08:13:23.105015108Z",
        "updated": "2020-06-02T08:13:23.105015108Z",
        "object_id": "5ed60a232c356a0001a7389f",
        "object_type": "sg_buckets",
        "object_name": "mybucket",
        "status": "pending",
        "status_detail": "",
        "last_error": "",
        "user_id": "5ec626c0f038943eb46b0af1",
        "job_tasks": null
      }
    ]
  }
}
....