---
sidebar: sidebar 
permalink: seapiref_regions.html 
keywords: netapp, keystone, regions, 
summary: Regioni Keystone 
---
= Regioni
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utilizzare i metodi elencati nella tabella seguente per creare, modificare ed eliminare le aree. Per le API che consentono di recuperare le aree, vedere API di amministrazione (Consumer).

|===
| Metodo HTTP | Percorso | Descrizione 


| `GET` | `/v2.1/regions` | Ottieni regioni. 


| `GET` | `/v2.1/regions/{name}` | Ottieni regioni per nome. 


| `POST` | `/v2.1/regions` | Creare una nuova regione. 


| `PUT` | `/v2.1/regions/{name}` | Modificare i dettagli di una regione. 


| `DELETE` | `/v2.1/regions/{name}` | Eliminare una regione. 
|===


== Attributi della regione

Nella tabella seguente sono elencati gli attributi della regione.

|===
| Attributo | Tipo | Descrizione 


| `id` | Stringa | L'identificatore univoco della regione. 


| `name` | Stringa | Il nome della regione. 


| `description` | Stringa | La descrizione della regione. 
|===


== Recuperare le regioni

Utilizzare il metodo elencato nella tabella seguente per recuperare tutte le regioni o un sottoinsieme di regioni.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `GET` | `/v2.1/regions` | Recuperare le regioni. | `offset` e. `limit`– vedere link:seapiref_netapp_service_engine_rest_apis.html#pagination>["Impaginazione comune"] 
|===
Attributi del corpo della richiesta richiesti: `none`

*Esempio di corpo della richiesta:*

....
none
....
*Esempio di corpo di risposta:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "total_records": 4,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 0,
    "limit": 1,
    "records": [
      {
        "id": "5e7bf44daab46c00014ce77f",
        "name": "au-east8",
        "description": "This is the new region description",
        "zones": []
      }
    ]
  }
}
....


== Recuperare una regione in base al nome

Utilizzare il metodo elencato nella tabella seguente per recuperare una regione in base al nome.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `GET` | `/v2.1/regions/{name}` | Recuperare una regione in base al nome. | `name (string)`: Il nome della regione. 
|===
Attributi del corpo della richiesta richiesti: `none`

*Esempio di corpo della richiesta:*

....
none
....
*Esempio di corpo di risposta:*

....
{
  "status": {
    "user_message": "string",
    "verbose_message": "string",
    "code": "string"
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5d2fb0fb4f47df00015274e3",
        "name": "au-east1",
        "description": "string",
        "zones": [
          "au-east1-a"
        ]
      }
    ]
  }
}
....


== Creare una regione

Utilizzare il metodo elencato nella tabella seguente per creare una regione.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `POST` | `/v2.1/regions` | Creare una nuova regione. | Nessuno 
|===
Attributi del corpo della richiesta richiesti: `name`

*Esempio di corpo della richiesta:*

....
{
  "name": "MyRegionName",
  "description": "DescriptionOfMyRegion"
}
....
*Esempio di corpo di risposta:*

....
{
  "status": {
    "user_message": "Okay. New resource created.",
    "verbose_message": "",
    "code": 201
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "id": "5e616f849b64790001fe9658",
        "name": "MyRegionName",
        "Description": "DescriptionOfMyRegion",
        "user_id": "5bbee380a2df7a04d43acaee",
        "created": "0001-01-01T00:00:00Z",
        "tags": null
      }
    ]
  }
}
....


== Modificare una regione

Utilizzare il metodo riportato nella tabella seguente per modificare una regione.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `PUT` | `/v2.1/regions/{name}` | Modificare una regione identificata dal nome. È possibile modificare il nome e la descrizione della regione. | `name (string)`: Il nome della regione. 
|===
Attributi del corpo della richiesta richiesti: `none`

*Esempio di corpo della richiesta:*

....
{
  "name": "MyRegionName",
  "description": "NewDescriptionOfMyRegion"
}
....
*Esempio di corpo di risposta:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "id": "5e616f849b64790001fe9658",
        "name": "MyRegionName",
        "description": "NewDescriptionOfMyRegion",
        "zones": []
      }
    ]
  }
}
....


== Eliminare una regione

Utilizzare il metodo riportato nella tabella seguente per eliminare una regione.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `DELETE` | `/v2.1/regions{name}` | Eliminare una singola regione identificata dal nome. Tutte le zone all'interno di una regione devono essere eliminate per prime. | `Name (string)`: Il nome della regione. 
|===
Attributi del corpo della richiesta richiesti: `none`

*Esempio di corpo della richiesta:*

....
none
....
*Esempio di corpo di risposta:*

....
No content for succesful delete
....