---
sidebar: sidebar 
permalink: seapiref_users.html 
keywords: netapp, keystone, users, 
summary: Utenti Keystone 
---
= Utenti
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utilizzare i metodi elencati nella tabella seguente per recuperare, creare, modificare ed eliminare i sottostruttivi.

|===
| Metodo HTTP | Percorso | Descrizione 


| `GET` | `/v2.1/users` | Recuperare un elenco di tutti gli utenti. 


| `GET` | `/v2.1/users/{id}` | Recuperare un utente in base all'ID utente. 


| `POST` | `/v2.1/users` | Creare un nuovo utente. 


| `PUT` | `/v2.1/users/{id}` | Modificare i dettagli di un utente. 


| `DELETE` | `/v2.1/users/{id}` | Eliminare un utente. 


| `GET` | `/v2.1/users/{username}` | Recuperare un utente in base al nome utente. 
|===


== Attributi dell'utente

Nella tabella seguente sono elencati gli attributi dell'utente.

|===
| Attributo | Tipo | Descrizione 


| `id` | Stringa | L'identificatore univoco dell'utente. 


| `username` | Stringa | Il nome utente. 


| `password` | Stringa | La password dell'utente. 


| `firstName` | Stringa | Il nome dell'utente. 


| `lastName` | Stringa | Il cognome dell'utente. 


| `displayName` | Stringa | Il nome visualizzato dell'utente. 


| `email` | Stringa | L'indirizzo e-mail dell'utente. 


| `phone` | Stringa | Il numero di telefono dell'utente. 


| `profileImageURL` | Stringa | L'URL dell'immagine del profilo dell'utente. 


| `tenant_id` | Stringa | L'identificatore principale del tenant per questo utente. 


| `tenancies` | –  a| 
La tenancy a cui appartiene l'utente; un array costituito da:

* `tenant_id`, e.
* `role_name`Questo è il ruolo dell'utente: User, admin, Read, partner, o root.




| `provider` | Stringa | Provider di autenticazione: `local` oppure `activeDirectory` 


| `provider data` | –  a| 
Dettagli del provider di autenticazione, costituiti da:

* `email_address`, e.
* `member_of` (appartenenza al gruppo)


|===


== Recuperare tutti gli utenti

Utilizzare il metodo elencato nella tabella seguente per recuperare tutti gli utenti.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `GET` | `/v2.1/users` | Recuperare tutti gli utenti. | Nessuno 
|===
Attributi del corpo della richiesta richiesti: `none`

*Esempio di corpo della richiesta:*

....
none
....
*Esempio di corpo di risposta:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "id": "5dddbe0ef071fe0001b889fd",
        "username": "TestUser3",
        "firstName": "Test",
        "lastName": "User",
        "displayName": "",
        "email": "testuser@netapp.com",
        "tenancies": [
          {
            "id": "5d914499869caefed0f39eee",
            "name": "MyOrg",
            "code": "myorg",
            "role": "admin"
          }
        ]
      }
    ]
  }
}
....


== Recuperare un utente in base all'ID

Utilizzare il metodo elencato nella tabella seguente per recuperare un utente in base all'ID.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `GET` | `/v2.1/users` | Recuperare un utente in base all'ID. | `id (string)`L'identificatore univoco dell'utente. 
|===
Attributi del corpo della richiesta richiesti: `none`

*Esempio di corpo della richiesta:*

....
none
....
*Esempio di corpo di risposta:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "id": "5e585df6896bd80001dd4b44",
        "username": "testuser01",
        "firstName": "",
        "lastName": "",
        "displayName": "",
        "email": "",
        "tenancies": [
          {
            "id": "5d914499869caefed0f39eee",
            "name": "MyOrg",
            "code": "myorg",
            "role": "user"
          }
        ]
      }
    ]
  }
}
....


== Recuperare un utente in base al nome utente

Utilizzare il metodo elencato nella tabella seguente per recuperare un utente in base al nome utente.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `GET` | `/v2.1/users` | Recuperare un utente in base al nome utente. | `username (string)`Il nome utente dell'utente. 
|===
Attributi del corpo della richiesta richiesti: `none`

*Esempio di corpo della richiesta:*

....
none
....
*Esempio di corpo di risposta:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "id": "5e61aa814559c20001df1a5f",
        "username": "MyName",
        "firstName": "MyFirstName",
        "lastName": "MySurname",
        "displayName": "CallMeMYF",
        "email": "user@example.com",
        "tenancies": [
          {
            "id": "5e5f1c4f253c820001877839",
            "name": "MyTenant",
            "code": "testtenantmh",
            "role": "user"
          }
        ]
      }
    ]
  }
}
....


== Creare un utente

Per creare un utente, utilizzare il metodo riportato nella tabella seguente.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `POST` | `/v2.1/users` | Creare un nuovo utente. | Nessuno 
|===
Attributi del corpo della richiesta richiesti: `username`, `tenant_id`, `tenancies, provider`

*Esempio di corpo della richiesta:*

....
{
  "username": "MyUser",
  "password": "mypassword",
  "firstName": "My",
  "lastName": "User",
  "displayName": "CallMeMyUser",
  "email": "user@example.com",
  "phone": "string",
  "profileImageURL": "string",
  "tenant_id": "5e7c3af7aab46c00014ce877",
  "tenancies": [
    {
      "tenant_id": "5e7c3af7aab46c00014ce877",
      "role_name": "admin"
    }
  ],
  "provider": "local",
  "provider_data": {
    "email": "user@example.com",
    "member_of": "string"
  }
}
....
*Esempio di corpo di risposta:*

....
{
  "status": {
    "user_message": "Okay. New resource created.",
    "verbose_message": "",
    "code": 201
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ed6f463129e5d000102f7e1",
        "username": "MyUser",
        "firstName": "My",
        "lastName": "User",
        "displayName": "CallMeMyUser",
        "email": "user@example.com",
        "tenancies": [
          {
            "id": "5e7c3af7aab46c00014ce877",
            "name": "MyTenant",
            "code": "mytenantcode",
            "role_name": "admin"
          }
        ]
      }
    ]
  }
}
....


== Modificare un utente in base all'ID

Per modificare un utente in base all'ID utente, utilizzare il metodo riportato nella tabella seguente.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `PUT` | `/v2.1/users/{id}` | Modificare un utente identificato dall'ID utente. È possibile modificare il nome utente, il nome visualizzato, la password, l'indirizzo e-mail, il numero di telefono, URL dell'immagine del profilo e dettagli della tenancy. | `id (string)`L'identificatore univoco dell'utente. 
|===
Attributi del corpo della richiesta richiesti: `none`

*Esempio di corpo della richiesta:*

....
{
  "password": "MyNewPassword",
   "firstName": "MyFirstName",
   "lastName": "MySurname",
   "displayName": "CallMeMYF",
   "email": "user@example.com",
   "phone": "string",
  "profileImageURL": "string",
  "tenant_id": "5e5f1c4f253c820001877839",
  "tenancies": [
    {
      "tenant_id": "5e5f1c4f253c820001877839",
      "role_name": "user"
    }
  ]
}
....
*Esempio di corpo di risposta:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "total_records": 1,
    "records": [
      {
        "id": "5e61aa814559c20001df1a5f",
        "username": "MyName",
        "firstName": "MyFirstName",
        "lastName": "MySurname",
        "displayName": "CallMeMYF",
        "email": "user@example.com",
        "tenancies": [
          {
            "id": "5e5f1c4f253c820001877839",
            "name": "MyTenant",
            "code": "testtenantmh",
            "role": "user"
          }
        ]
      }
    ]
  }
}
....


== Eliminare un utente in base all'ID

Utilizzare il metodo riportato nella tabella seguente per eliminare un utente in base all'ID.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `DELETE` | `/v2.1/users/{name}` | Eliminare l'utente identificato dall'ID. | `id (string)`L'identificatore univoco dell'utente. 
|===
Attributi del corpo della richiesta richiesti: `none`

*Esempio di corpo della richiesta:*

....
none
....
*Esempio di corpo di risposta:*

....
No content for succesful delete
....