---
sidebar: sidebar 
permalink: seapiref_subtenants.html 
keywords: netapp, keystone, subtenants, 
summary: Keystone 
---
= Subtenant
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utilizzare i metodi elencati nella tabella seguente per recuperare, creare, modificare ed eliminare i sottostruttivi.

|===
| Metodo HTTP | Percorso | Descrizione 


| `GET` | `/v2.1/subtenants` | Recuperare i subtenant. 


| `GET` | `/v2.1/subtenants/{id}` | Recuperare un sottenant in base all'ID del sottenant. 


| `POST` | `/v2.1/subtenants`` | Creare un nuovo sottotenant. 


| `PUT` | `/v2.1/subtenants/{id}` | Modificare i dettagli di un sottotenant. È possibile modificare il nome del sottotenant. 


| `DELETE` | `/v2.1/subtenants/{id}` | Eliminare un sottotenant. 
|===


== Attributi del sottotenant

Nella tabella seguente sono elencati gli attributi dei subtenant.

|===
| Attributo | Tipo | Descrizione 


| `id` | Stringa | L'identificatore univoco del subtenant. 


| `name` | Stringa | Il nome del sottotenente. 


| `code` | Stringa | Codice specificato dal cliente (o predefinito) che rappresenta il sottenant. 


| `tenant_id` | Stringa | L'identificativo del tenant a cui appartiene il subtenant. 
|===


== Recuperare tutti i subtenant

Utilizzare il metodo elencato nella tabella seguente per recuperare tutti i subtenant o un sottoinsieme di tutti i subtenant. Specificare un `tenant_id` restituirà solo i subtenant appartenenti a quel tenant.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `GET` | `/v2.1/subtenants` | Recuperare i subtenant. | `tenant_id`: (Facoltativo) Restituisci i subtenant appartenenti al tenant specificato. offset e limite– vedere 
|===
Attributi del corpo della richiesta richiesti: `none`

*Esempio di corpo della richiesta:*

....
none
....
*Esempio di corpo di risposta:*

....
{
  "status": {
    "user_message": "Okay. Returned 2 records.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 2,
    "total_records": 202,
    "sort_by": "created",
    "order_by": "desc",
    "offset": 0,
    "limit": 2,
    "records": [      {
        "id": "5e7c3af8aab46c00014ce878",
        "description": "",
        "name": "MySubtenant",
        "code": "mysubtenant",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant"
      },
      {
        "id": "5d9144f3869caefed0f39f82",
        "description": "",
        "name": "Mysubtenant2",
        "code": "myothersubtenant",
        "tenant_id": "5d914499869caefed0f39eee",
        "tenant": "MyTenant"
      }
    ]
  }
}
....


== Recuperare un sottotenant in base all'ID

Utilizzare il metodo riportato di seguito per recuperare un sottenant in base all'ID.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `GET` | `/v2.1/subtenants/{id}` | Recuperare il sottotenant specificato dall'ID. | `id (string)`: L'identificatore univoco del subtenant. 
|===
Attributi del corpo della richiesta richiesti: `none`

*Esempio di corpo della richiesta:*

....
none
....
*Esempio di corpo di risposta:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5e7c3af8aab46c00014ce878",
        "description": "",
        "name": "MySubtenant",
        "code": "subtenantcode",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant"
      }
    ]
  }
}
....


== Creare un sottotenant

Utilizzare il metodo elencato nella tabella seguente per creare un sottostruttura.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `POST` | `/v2.1/subtenants` | Creare un nuovo sottotenant. | Nessuno 
|===
Attributi del corpo della richiesta richiesti: `name`, `code`, `tenant_id`

*Esempio di corpo della richiesta:*

....
{
  "name": "MySubtenant",
  "code": "mynewsubtenant",
  "tenant_id": "5ed5ac802c356a0001a735af"
}
....
*Esempio di corpo di risposta:*

....
{
  "status": {
    "user_message": "Okay. New resource created.",
    "verbose_message": "",
    "code": 201
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ecefbbef418b40001f20bd6",
        "description": "",
        "name": "MyNewSubtenant",
        "code": "mynewsubtenant",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant"
      }
    ]
  }
}
....


== Modificare un sottotenant in base all'ID

Utilizzare il metodo elencato nella tabella seguente per modificare un sottenant in base all'ID.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `PUT` | `/v2.1/subtenants/{id}` | Modificare il sottostruttura specificato dall'ID. È possibile modificare il nome del sottotenant. | `id (string)`: L'identificatore univoco del subtenant. 
|===
Attributi del corpo della richiesta richiesti: `name`

*Esempio di corpo della richiesta:*

....
{
  "name": "MyModifiedSubtenant"
}
....
*Esempio di corpo di risposta:*

....
{
  "status": {
    "user_message": "Okay. Returned 1 record.",
    "verbose_message": "",
    "code": 200
  },
  "result": {
    "returned_records": 1,
    "records": [
      {
        "id": "5ecefbbef418b40001f20bd6",
        "description": "",
        "name": "MyNewSubtenant",
        "code": "mynewsubtenant",
        "tenant_id": "5e7c3af7aab46c00014ce877",
        "tenant": "MyTenant"
      }
    ]
  }
}
....


== Eliminare un sottenant in base all'ID

Utilizzare il metodo elencato nella tabella seguente per eliminare un sottenant in base all'ID.

|===
| Metodo HTTP | Percorso | Descrizione | Parametri 


| `DELETE` | `/v2.1/subtenants/{id}` | Eliminare il sottostrato specificato dall'ID. | `id (string)`: L'identificatore univoco del subtenant. 
|===
Attributi del corpo della richiesta richiesti: `none`

*Esempio di corpo della richiesta:*

....
none
....
*Esempio di corpo di risposta:*

....
No content for succesful delete
....