---
sidebar: sidebar 
permalink: sewebiug_track_a_service_request.html 
keywords: netapp, keystone, track, service, request, 
summary: Keystone tiene traccia di una richiesta di servizio 
---
= Tenere traccia di una richiesta di servizio
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Una richiesta di servizio segue il processo descritto in questa sezione.

La seguente tabella fornisce un elenco degli stati delle richieste di servizio.

|===
| Stato | Descrizione 


| Novità | Si tratta di una richiesta creata di recente. 


| Aprire | La richiesta è in fase di revisione/adempimento. 


| In sospeso | La richiesta è in attesa di azione da parte di terzi (ad esempio, in attesa di ulteriori informazioni). 


| Risolto | La richiesta è stata risolta. 


| In attesa | La richiesta è in attesa di un'attività che non è sotto il controllo del supporto e può richiedere del tempo prima che la richiesta possa essere affrontata. 


| Chiuso | La richiesta è chiusa. 
|===
È possibile seguire lo stato di una richiesta di servizio esaminando lo stato in NetApp Service Engine, come descritto di seguito, oppure seguire lo stato nelle e-mail automatiche inviate come parte del processo.

. Dal menu, selezionare *supporto > Richieste di servizio*. L'elenco viene filtrato in base alla priorità predefinita `Urgent`.
. Selezionare la priorità e lo stato richiesti per visualizzare l'elenco della richiesta di servizio.
. Individuare la richiesta di servizio nell'elenco e visualizzarne lo stato in `Status` colonna.

