---
sidebar: sidebar 
permalink: sewebiug_create_file_share_from_snapshot.html 
keywords: netapp, keystone, create, file share, snapshot 
summary: Creare una condivisione di file da uno snapshot 
---
= Creare una condivisione di file da uno snapshot
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile creare una nuova condivisione di file da uno snapshot esistente. La nuova condivisione file, clonata dallo snapshot, ha le stesse proprietà della condivisione file da cui viene creata lo snapshot.

.Fasi
. Selezionare *SERVIZI FILE* dal riquadro di navigazione a sinistra e selezionare *condivisioni*.
. Fare clic su *Create Share* (Crea condivisione) e selezionare *Clone from snapshot* (Clona dallo snapshot). In alternativa, se si conosce la condivisione di cui si desidera utilizzare lo snapshot per la clonazione, è possibile individuare la condivisione file e fare clic sul pulsante di copia accanto. La condivisione deve essere in uno stato operativo. Per informazioni sugli stati degli oggetti, vedere link:sewebiug_netapp_service_engine_web_interface_overview.html#object-states["stati degli oggetti"]. Viene visualizzata la schermata *Create Share from Snapshot* (Crea condivisione da snapshot) con tutte le condivisioni di file per il tenant. È possibile filtrare le condivisioni di file in base all'area, alla zona e al sottenant. È possibile selezionare qualsiasi condivisione di file in stato operativo.
. Selezionare la casella di controllo accanto alla condivisione file desiderata e fare clic su *Avanti*. Vengono visualizzate le istantanee per la condivisione file.
+

NOTE: Per la condivisione di file selezionata, se sono state create alcune snapshot nell'ambiente SnapCenter al di fuori del motore di servizio NetApp, è possibile trovare tali snapshot importate ed elencate per la selezione. È possibile selezionare queste snapshot importate e clonare le nuove condivisioni di file.

+
È possibile cercare uno snapshot specifico o selezionare il tipo di pianificazione per filtrare gli snapshot.

. Selezionare la casella di controllo accanto allo snapshot da cui si desidera clonare e fare clic su *Avanti*. La nuova condivisione file eredita le proprietà dello snapshot selezionato.
. Aggiungere *Nome* e *percorso di condivisione*. Aggiornare le altre impostazioni, ad esempio l'assegnazione di un *livello di servizio* e fare clic su *Crea*. Selezionare il livello di servizio più adatto alle proprie esigenze.


.Al termine
* Solo per condivisioni di tipo CIFS: Per rendere disponibili le condivisioni in base al nome host, l'amministratore di dominio deve aggiornare i record DNS con il nome del server CIFS e l'indirizzo IP. In caso contrario, la condivisione è accessibile solo tramite l'indirizzo IP. Ad esempio:
+
** Una volta aggiornati i record DNS, utilizzare il nome host o l'IP per accedere alla condivisione, ad esempio file://hostname/share["nome host/condivisione"^] oppure file://IP/share["IP/share"^]
** Se non vengono aggiornati i record DNS, è necessario utilizzare l'indirizzo IP per accedere alla condivisione, ad esempio file://IP/share["IP/share"^]


* *Create Share* viene eseguito come processo asincrono. È possibile:
+
** Verificare lo stato del lavoro nell'elenco dei lavori. Per informazioni sul monitoraggio dei processi, vedere link:sewebiug_netapp_service_engine_web_interface_overview.html#jobs-and-job-status-indicator["qui"].
** Al termine del lavoro, controllare lo stato della condivisione nell'elenco *shares*.



