---
sidebar: sidebar 
permalink: sewebiug_back_up_file_shares_and_disks.html 
keywords: netapp, keystone, backup, create, modify, delete, restore 
summary: Creare, modificare ed eliminare backup o ripristini dai backup 
---
= Backup di condivisioni di file e dischi
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile definire policy di backup per creare backup dei volumi (condivisioni di file e dischi) nel proprio ambiente e gestire in remoto più copie dei volumi primari.


NOTE: I backup vengono creati automaticamente nel sistema quando si crea o si modifica un criterio di backup per un volume. Non è possibile creare un backup dall'interfaccia di NetApp Service Engine. È possibile utilizzare l'API di backup per creare e gestire i backup dei volumi.

Per ulteriori informazioni, vedere link:seapiref_backups_apis.html["API di backup"]

Il backup dei volumi di origine viene attivato tramite la tecnologia NetApp SnapMirror abilitata con i servizi di abbonamento Keystone. Per ulteriori informazioni, vedere link:index.html#flex-subscription["qui"].

Quando si crea o si modifica un volume, viene definita la relativa pianificazione di backup. Il backup viene eseguito agli intervalli previsti e memorizzato in un sistema di destinazione. Affinché i backup funzionino, è necessario stabilire la relazione di SnapMirror con l'ambiente di destinazione. Le condivisioni di file replicate e i dischi di diverse zone vengono memorizzati su una VM di storage di backup dedicata (macchina virtuale di storage, nota anche come SVM) su ciascun cluster. I backup possono essere eseguiti tra due cluster ONTAP separati in zone diverse.

Le policy di backup standard supportate da NetApp Service Engine sono:

* Ad hoc
* Ogni giorno
* Settimanale
* Mensile


Per i backup creati nel back-end, i volumi devono essere in un `Operational` stato. Per ulteriori informazioni sugli stati degli oggetti, vedere operativo (per l'oggetto di origine di un backup) link:sewebiug_netapp_service_engine_web_interface_overview.html#object-states["qui"].

Se il volume non segue le policy di backup standard supportate da NetApp Service Engine, è possibile link:sewebiug_raise_a_service_request.html["inoltrare una richiesta di servizio"] Della categoria *Volume non standard* per risolvere il problema.

È possibile visualizzare l'elenco dei backup creati per le condivisioni di file e i dischi nella pagina *Backup*. I backup vengono visualizzati in base al tenant selezionato.



== Modificare una policy o una pianificazione di backup

Quando si creano o modificano condivisioni di file e dischi, è possibile definire le relative policy di backup. I backup vengono eseguiti nel back-end in base alle policy specificate dall'utente. Per ulteriori informazioni, vedere: link:sewebiug_create_a_new_file_share.html["creare una condivisione di file"] oppure link:sewebiug_create_a_new_disk.html["creare un disco"].

.Fasi
. Attiva *Backup Policy*.
. Specificare la zona di backup e il numero di backup da eseguire su base adhoc, giornaliera, settimanale e/o mensile.
. Fare clic su *Create* (Crea).



NOTE: È inoltre possibile pianificare i backup modificando il criterio di backup per una condivisione di file o un disco esistente.



== Modificare o scollegare l'origine di un backup

Per un oggetto di backup selezionato di una condivisione di file o di un disco, è possibile disattivare il backup o scollegare l'oggetto di backup dalla relativa origine e renderlo un backup orfano. Questa operazione interrompe la relazione di SnapMirror con l'origine. È inoltre possibile modificare il numero di backup da eseguire su base adhoc, giornaliera, settimanale e/o mensile.

.Fasi
. Nel riquadro di navigazione a sinistra, fare clic su *BACKUP*. È possibile visualizzare l'elenco dei backup creati per tutti gli oggetti dell'ambiente.
. Individuare il backup nell'elenco (ricerca in base al nome del volume) e fare clic sull'icona di modifica alla fine della riga.
. Apportare modifiche all'origine del backup e al numero di ciascun tipo di backup, secondo necessità. È possibile interrompere la relazione di SnapMirror con il volume di origine cambiando l'origine del backup in *None (Orphaned)*. I backup vengono conservati come backup orfani per il ripristino anche quando i volumi di origine vengono cancellati. Lo stato dell'oggetto di backup cambia e lo stato del volume di origine (orfano o cancellato) viene aggiunto al nome del volume di origine sullo stesso elenco. Per informazioni sugli stati degli oggetti, vedere link:sewebiug_netapp_service_engine_web_interface_overview.html#Object-states["qui"]
. Fare clic su *fine*. Lo snapshot viene modificato. Se è stata interrotta la relazione di SnapMirror con l'origine, ovvero l'oggetto di backup orfano, il nome dell'origine nella scheda *Backup* viene visualizzato come `deleted`.



NOTE: È inoltre possibile interrompere la relazione di SnapMirror con il volume di origine disattivando *Backup Policy* per il volume dalle schermate Create Share/Edit Share (Crea condivisione/Modifica condivisione) e Create Disk/Edit Disk (Crea disco/Modifica disco).



== Richiedere supporto per backup e ripristino

È possibile link:sewebiug_raise_a_service_request.html["inoltrare una richiesta di servizio"] per ripristinare una condivisione di file o un disco da un punto di ripristino specifico.

.Fasi
. Selezionare *SUPPORT* dal riquadro di navigazione a sinistra e selezionare *Service Requests* (Richieste di servizio).
. Fare clic su *Nuova richiesta di servizio*.
. Selezionare *Backup Restore* come categoria per la richiesta di servizio.
. Specificare altri dettagli e procedere.




== Rimuovere un oggetto di backup

L'eliminazione di un volume di backup inutilizzato aumenta lo spazio di storage. Per eliminare un volume di backup e i punti di ripristino dell'origine eliminata, è necessario utilizzare l'API di backup.


NOTE: Quando un backup viene cancellato, tutti i punti di ripristino per il backup vengono cancellati. Inoltre, anche se si elimina una condivisione di file o un disco primario, il backup viene conservato come backup orfano con tutti i punti di ripristino per il ripristino.
