---
sidebar: sidebar 
permalink: sewebiug_modify_a_file_share.html 
keywords: netapp, keystone, modify, file, share, 
summary: Keystone modifica una condivisione file 
---
= Modificare una condivisione file
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
È possibile modificare il nome della condivisione, il livello di servizio, la capacità, la policy di snapshot, la policy di esportazione, Access Control List (ACL) e tag in una condivisione file.


NOTE: Utilizzando questo metodo, è possibile spostare le condivisioni a diversi livelli di servizio, se disponibili. È possibile modificare il tipo di condivisione solo se il server supporta i rispettivi servizi.

.Prima di iniziare
La condivisione file deve essere in stato operativo. Per informazioni sugli stati dei volumi e sui passaggi da intraprendere per renderli operativi, vedere link:sewebiug_view_disks.html["Visualizzare i dischi"] e. link:sewebiug_netapp_service_engine_web_interface_overview.html#object-states["stati degli oggetti"]

.Fasi
. Visualizzare il link:sewebiug_view_shares.html#view-shares["Shares"].
. Individuare la condivisione nell'elenco e fare clic sull'icona Modifica relativa alla condivisione. Per ulteriori informazioni sull'utilizzo degli elementi negli elenchi, vedere link:sewebiug_netapp_service_engine_web_interface_overview.html#list-view["Azioni di visualizzazione elenco"]).
. Apportare le modifiche necessarie; per le descrizioni dei campi, vedere link:sewebiug_create_a_new_file_share.html["Creare una nuova condivisione file"].
. Fare clic su *fine*. In questo modo viene creato un lavoro per modificare la condivisione.


.Al termine
La modifica della condivisione viene eseguita come processo asincrono. È possibile:

* Verificare lo stato del lavoro nell'elenco dei lavori. Per informazioni sul monitoraggio dei processi, vedere link:sewebiug_netapp_service_engine_web_interface_overview.html#jobs-and-job-status-indicator["qui"].
* Al termine del lavoro, controllare lo stato della condivisione nell'elenco delle condivisioni.

