---
sidebar: sidebar 
permalink: sewebiug_managing_subscribed_services_overview.html 
keywords: netapp, keystone, managing, cloud, services, overview, 
summary: 'Keystone: Panoramica sulla gestione dei servizi cloud' 
---
= Panoramica
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Una volta registrati con NetApp Service Engine, puoi gestire i servizi CVS (Cloud Volumes Services) attraverso il portale Web di NetApp Service Engine. Ciò include:

* Azure NetApp Files (ANF)
* (Futuro) Amazon Web Services (AWS)
* (Futuro) Google Cloud Platform (GCP)
+
È possibile registrare solo gli abbonamenti CVS esistenti con NetApp Service Engine; per creare un nuovo abbonamento, creare l'abbonamento CVS nel modo normale e registrarlo con NetApp Service Engine utilizzando le credenziali di abbonamento.

+
Questa sezione descrive come gestire i servizi cloud




NOTE: La gestione dei servizi cloud richiede l'accesso di Customer Admin.

È possibile:

* Visualizzare un elenco di servizi cloud
* Aggiungi un servizio cloud
* Modificare i dettagli del servizio cloud
* Eliminare un servizio cloud

