---
sidebar: sidebar 
permalink: sewebiug_raise_a_service_request.html 
keywords: netapp, keystone, raise, service, request, NetApp GSSC, tenant support 
summary: Keystone presenta una richiesta di servizio 
---
= Inoltrare una richiesta di servizio
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La schermata Service Requests (Richieste di servizio) consente di inoltrare nuove richieste di servizio in qualità di amministratore del partner per le sottoscrizioni del o dei tenant e di inviarle al proprio team di supporto o a NetApp GSSC.

In qualità di amministratore del partner, è possibile visualizzare il riepilogo delle richieste di servizio più recenti per un tenant, ordinate in base alla priorità e al tempo di creazione, nel widget *Richieste di servizio* della dashboard. È inoltre possibile accedere alla schermata Richieste di servizio per cercare e visualizzare i dettagli di tutte le richieste di servizio inoltrate nel proprio ambiente.

Per creare una nuova richiesta di servizio, seguire questa procedura.

.Fasi
. Dal menu, selezionare *SUPPORT > Service Requests* (SUPPORTO > Richieste di servizio) e fare clic su *New Service Request* (Nuova richiesta di servizio).
. Nella pagina Nuova richiesta di servizio, selezionare la categoria e la priorità della richiesta, quindi fare clic su *Avanti*. Viene visualizzata la schermata *Dettagli*.



NOTE: I campi della schermata Dettagli cambiano in base alla categoria selezionata. In questa schermata, inserire i dettagli relativi alla categoria selezionata della richiesta di servizio.

. Inserire i dettagli richiesti. Fare clic su *Avanti*.
. Esaminare i dettagli della richiesta. Se si desidera correggere qualsiasi problema, utilizzare il pulsante Indietro per tornare alla pagina precedente e correggere i dettagli. Se tutti i dettagli sono corretti, fare clic su *Invia*.
. La richiesta di servizio viene creata ed elencata nella schermata Richieste di servizio. Una richiesta di servizio aperta di recente ha un `New` stato.


Viene inviato un messaggio di posta elettronica al richiedente per indicare che la richiesta è stata creata. L'e-mail viene inviata all'indirizzo di posta elettronica registrato per l'utente del NetApp Service Engine richiedente.
