---
sidebar: sidebar 
permalink: sewebiug_create_an_adhoc_snapshot_of_a_disk.html 
keywords: netapp, keystone, create, adhoc, snapshot, disk 
summary: 'Keystone crea un"istantanea adhoc di un disco' 
---
= Creare uno snapshot ad hoc di un disco
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
In questa sezione viene descritto come creare uno snapshot ad hoc di un disco.

.Fasi
. Visualizzare il link:sewebiug_view_disks.html#view-disks["Elenco dei dischi"].
. Individuare il disco nell'elenco e fare clic sull'icona di snapshot del disco. Per ulteriori informazioni sull'utilizzo degli elementi negli elenchi, vedere link:sewebiug_netapp_service_engine_web_interface_overview#list-view["Azioni di visualizzazione elenco"]).
. Nella finestra di dialogo Create Snapshot (Crea istantanea), immettere un nome per l'istantanea e fare clic su *Create* (Crea).


.Al termine
La disponibilità dello snapshot potrebbe richiedere alcuni minuti. Se disponibile, è possibile creare un altro disco clonando questo snapshot. Per ulteriori informazioni, vedere link:sewebiug_create_a_disk_from_a_snapshot.html["Creare un disco da uno snapshot"].
