---
sidebar: sidebar 
permalink: sewebiug_view_the_object_storage_group_and_users.html 
keywords: netapp, keystone, view, object, storage, group, users, 
summary: Keystone visualizza il gruppo di storage a oggetti e gli utenti 
---
= Visualizzare utenti e gruppi di storage a oggetti
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
L'elenco User Management (Gestione utenti) visualizza gli utenti e i gruppi di storage a oggetti per un determinato sottenant.

.Fasi
. Dal menu, selezionare *OBJECT STORAGE > User Management* (ARCHIVIAZIONE OGGETTI > Gestione utenti).
. Se necessario, utilizzare il menu a discesa del sottotenant per selezionare un altro sottotenant.
. Utilizzare le schede *utenti* e *gruppi* per alternare la visualizzazione tra utenti e gruppi.
+
** L'elenco Users (utenti) visualizza gli utenti dello storage a oggetti definiti per il sottenant selezionato. Per ogni utente, vengono visualizzati il nome e i gruppi di storage a oggetti a cui appartengono.
** L'elenco Groups (gruppi) visualizza i gruppi di storage a oggetti definiti per il sottenant selezionato. Visualizza il nome del gruppo e il criterio S3 assegnati a tale gruppo. Per informazioni sui gruppi di bucket e sulle policy S3, vedere https://docs.netapp.com/us-en/storagegrid-116/s3/bucket-and-group-access-policies.html#access-policy-overview["Policy di accesso a bucket e gruppi"].
+
Per ulteriori informazioni sull'utilizzo delle funzioni di un elenco, vedere link:sewebiug_netapp_service_engine_web_interface_overview.html#list-view-actions["Azioni di visualizzazione elenco"].




