---
sidebar: sidebar 
permalink: sewebiug_add_a_subscribed_service.html 
keywords: netapp, keystone, add, cloud, service, 
summary: Keystone aggiunge un servizio cloud 
---
= Aggiungi un servizio cloud
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Questa sezione descrive come aggiungere un servizio cloud.

Il motore di servizi NetApp supporta Azure NetApp Files.

.Prima di iniziare
Sono necessarie le informazioni sui servizi cloud, incluse le credenziali per connettersi al servizio. Le informazioni variano in base al tipo di servizio cloud.

.Fasi
. Selezionare *Cloud Services* dal menu.
. Fare clic su *Create* (Crea).
. Nella pagina Create Cloud Service (Crea servizio cloud), selezionare il tipo di servizio cloud e completare le informazioni pertinenti per quel tipo di servizio:
+
*Azure:*

+
.. Selezionare il sottotenant.
.. Immettere un nome per l'ambiente di lavoro OCCM che verrà creato per il servizio.
.. Immettere l'ID Azure Directory (tenant), l'ID client Azure, il segreto client Azure e il nome del servizio cloud.


. Specificare i tag per il servizio, se necessario.
. Fare clic su *Create* (Crea).

