---
sidebar: sidebar 
permalink: sewebiug_managing_azure_volumes.html 
keywords: netapp, keystone, managing, azure, volumes, 
summary: Keystone che gestisce i volumi Azure 
---
= Gestione dei volumi Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
In questa sezione viene descritto come gestire i volumi Azure.


NOTE: La gestione dei volumi Azure richiede l'accesso dell'amministratore del cliente.

In questa sezione viene descritto come eseguire le seguenti operazioni:

* Visualizzare un elenco di volumi Azure.
* Aggiungere un volume Azure.
* Modificare i dettagli del volume Azure.
* Eliminare un volume Azure.




== Visualizzare un elenco di volumi Azure

L'elenco Azure Volumes (volumi Azure) visualizza un elenco di pool di volumi Azure per un sottostrato e una posizione specificati. Per visualizzare l'elenco, selezionare *FILE SERVICES > Azure Volumes* dal menu.

L'elenco visualizza semplici informazioni su ciascun volume Azure. Le icone di azione accanto a ciascun volume Azure consentono di modificare o eliminare il volume Azure.



== Aggiungere un volume Azure

In questa sezione viene descritto come aggiungere un volume Azure.

.Prima di iniziare
Sono necessari:

* Il sottenant a cui appartiene il volume Azure
* L'account ANF
* Azure Virtual Network (VNET) e Subnet
* Il pool di capacità per ospitare il volume
* Un nome per il volume
* Il percorso del file
* La quota (dimensione) del volume


.Fasi
. Selezionare *FILE SERVICES > Azure Volumes* dal menu.
. Fare clic su *Create* (Crea).
. Nella finestra di dialogo Create Azure Volume (Crea volume Azure), specificare il sottenant, l'account ANF, VNET, la subnet, il pool di capacità, il nome del volume, il percorso del file e la quota. Assicurarsi di immettere un percorso di file univoco per la creazione di un volume.
. Se necessario, aggiungere tag al volume.
. Fare clic su *Create* (Crea). Quando viene creato un volume Azure, lo stato del volume diventa `Succeeded` (Può essere visualizzato nell'elenco Azure Volumes).




== Modificare i dettagli del volume Azure

Utilizzare questo metodo per modificare i dettagli di un volume Azure. È possibile modificare il percorso e la quota del file e aggiungere o rimuovere tag.

.Fasi
. Selezionare *FILE SERVICES > Azure Volumes* dal menu.
. Individuare il volume Azure dall'elenco e fare clic sull'icona di modifica.
. Nella finestra di dialogo Manage Azure Volume (Gestisci volume Azure), apportare le modifiche necessarie. Se si modifica il percorso o la quota del file, assicurarsi che il percorso del file sia univoco e che la quota non superi la quota disponibile nel pool.
. Fare clic su *Aggiorna*.




== Eliminare un volume Azure

Utilizzare questo metodo per eliminare un volume Azure.

.Fasi
. Selezionare *FILE SERVICES > Azure Volumes* dal menu.
. Individuare il volume Azure nell'elenco e fare clic sull'icona di eliminazione.
. Nella finestra di dialogo Conferma eliminazione, immettere il nome del volume Azure da eliminare.
. Fare clic su *Conferma*.

