---
sidebar: sidebar 
permalink: sewebiug_working_with_object_storage_overview.html 
keywords: netapp, keystone, working, object, storage, overview, 
summary: 'Keystone Panoramica sull"utilizzo dello storage a oggetti' 
---
= Panoramica
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Lo storage a oggetti richiede un abbonamento al servizio di storage a oggetti. Quando un servizio di storage a oggetti è disponibile come parte della sottoscrizione, lo storage deve essere inizializzato prima di poter essere utilizzato.

Con lo storage a oggetti, gli oggetti vengono memorizzati nei bucket S3. L'accesso ai bucket S3 viene gestito tramite autorizzazioni impostate sui gruppi di storage a oggetti. Agli utenti dello storage a oggetti viene concessa l'appartenenza a uno o più gruppi di storage a oggetti, ereditando le autorizzazioni dall'appartenenza al gruppo.

Ogni utente dello storage a oggetti dispone di chiavi S3 associate che consentono l'accesso allo storage a oggetti.


NOTE: L'accesso allo storage a oggetti avviene tramite un browser compatibile con S3.

In questa sezione viene descritto come gestire lo storage a oggetti, tra cui:

* Inizializzare lo storage a oggetti.
* Creare bucket S3.
+
Non è possibile eliminare i bucket S3 attraverso il portale Web NetApp Service Engine; eliminarli utilizzando un browser compatibile con S3.

* Creare e gestire gruppi di storage a oggetti.
* Creare e gestire gli utenti dello storage a oggetti, inclusa la creazione di chiavi S3.

