---
sidebar: sidebar 
permalink: sewebiug_create_an_s3_key_for_a_user.html 
keywords: netapp, keystone, create, S3, key, user, 
summary: Keystone crea una chiave S3 per un utente 
---
= Creare una chiave S3 per un utente
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utilizzare questo metodo per creare una chiave S3 per un utente.

Assicurarsi di acquisire la chiave subito dopo la creazione. Dopo la creazione, non è possibile recuperare i dettagli delle chiavi.

.Fasi
. Visualizzare l'utente dello storage a oggetti link:sewebiug_view_the_object_storage_group_and_users.html["Visualizzare utenti e gruppi di storage a oggetti"].
. Assicurarsi di aver selezionato il subtenant corretto e di aver fatto clic sulla scheda *Users* (utenti).
. Individuare l'utente nell'elenco e fare clic sull'icona principale del gruppo.
+
Per ulteriori informazioni sull'utilizzo degli elementi negli elenchi, vedere link:sewebiug_netapp_service_engine_web_interface_overview.html#list-view-actions["Azioni di visualizzazione elenco"].

. Viene visualizzata la finestra di dialogo *Manage S3 Keys* (Gestisci chiavi S3) che mostra l'elenco delle chiavi per l'utente. Per informazioni sui tasti, vedere https://docs.netapp.com/us-en/storagegrid-116/s3/bucket-and-group-access-policies.html#specify-permissions-in-a-policy["Specificare le autorizzazioni in un criterio"].
. Se non sono presenti chiavi per l'utente, fare clic su *Create S3 Key* (Crea chiave S3) per visualizzare i campi per creare una chiave.
. Se si desidera che la chiave scada, specificare la data di scadenza e l'ora di scadenza in UTC. In caso contrario, lasciare i valori predefiniti in questi campi.
. Per creare la chiave, fare clic sul segno di spunta. Viene visualizzata la finestra di dialogo *S3 Key Details* (Dettagli chiave S3) che mostra la chiave di accesso e la chiave segreta.
. Copiare le chiavi di accesso e le chiavi segrete in preparazione per informare l'utente dei dettagli.
+
Assicurarsi di acquisire i dettagli principali prima di chiudere la finestra di dialogo *S3 Key Details* (Dettagli chiave S3). Dopo la chiusura, i dettagli chiave verranno oscurati e non sarà possibile recuperarli.

. Fare clic su *Chiudi*.
. Fare nuovamente clic su *Chiudi* per chiudere la finestra di dialogo Gestisci chiavi S3.

