---
sidebar: sidebar 
permalink: sewebiug_alerts.html 
keywords: netapp, keystone, alert, create, custom alert 
summary: Creare e gestire gli avvisi 
---
= Creare e gestire gli avvisi
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Gli avvisi sono messaggi che vengono attivati automaticamente o creati manualmente per condividere informazioni sugli eventi critici all'interno dell'ambiente.

Quando si esegue il provisioning dello storage, vengono attivati avvisi automatici nei seguenti scenari:

* Il nuovo disco o la nuova condivisione di file spinge l'abbonamento in burst
* Il provisioning del nuovo disco o file share viene eseguito su un nuovo abbonamento
* La capacità consumata nell'ambito dell'abbonamento ha superato la capacità di soglia o è vicina alla capacità impegnata


La schermata *Alerts* (Avvisi) consente di visualizzare gli avvisi generati dal sistema e dall'utente nel proprio ambiente.

È inoltre possibile creare avvisi personalizzati e visualizzarli ad altri utenti. Possono visualizzare e ignorare gli avvisi per se stessi e per altri utenti all'interno del proprio tenancy, come richiesto.



== Creare un avviso nell'ambiente multi-tenant

Gli amministratori dei partner possono creare e inviare manualmente avvisi a un singolo tenant o a tutti i tenant del proprio ambiente.


NOTE: È possibile chiudere un avviso creato. Tuttavia, viene respinto solo per i locatari che non l'hanno ancora vista.

.Fasi
. Selezionare *AMMINISTRAZIONE* > *Avvisi* dal menu.
. Fare clic su *Crea avviso*.
. Nella schermata *Create alert* (Crea avviso), selezionare lo stato e il tenant a cui si desidera inviare l'avviso, quindi aggiungere il messaggio.
+

NOTE: Se si desidera inviare l'avviso a tutti i tenant del proprio ambiente, selezionare "tutti".

. Fare clic su *Create* (Crea). Viene creato il nuovo avviso.




== Crea un avviso nella tua tenancy

Gli amministratori dei tenant possono creare e inviare avvisi manualmente a tutti gli utenti del proprio ambiente.


NOTE: È possibile chiudere un avviso creato. Tuttavia, viene respinto solo per gli utenti che non l'hanno ancora visualizzata.

.Fasi
. Selezionare *AMMINISTRAZIONE* > *Avvisi* dal menu.
. Fare clic su *Crea avviso*.
. Nella schermata *Create alert* (Crea avviso), selezionare lo stato e aggiungere il messaggio.
. Fare clic su *Create* (Crea). Viene creato il nuovo avviso.

