---
sidebar: sidebar 
permalink: sewebiug_modify_user_details.html 
keywords: netapp, keystone, modify, user, details, 
summary: 'Keystone modifica i dettagli dell"utente' 
---
= Modificare i dettagli dell'utente
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utilizzare questo metodo per modificare i dettagli di un utente. È possibile:

* Modificare il nome, il cognome e il nome visualizzato dell'utente.
* Aggiungere o rimuovere le tenancy a cui l'utente ha accesso.
* Modificare il ruolo dell'utente in ogni tenancy a cui l'utente ha accesso.


.Fasi
. Selezionare *AMMINISTRAZIONE > utenti*.
. Individuare l'utente nell'elenco e fare clic sull'icona Edit (Modifica).
. Nella finestra di dialogo Edit User (Modifica utente), apportare le modifiche desiderate.
. Per modificare il ruolo dell'utente in un tenancy, individuare il tenancy nell'elenco tenancy e selezionare il nuovo ruolo.
. Per concedere all'utente l'accesso a un altro tenancy, fare clic su *Add Tenancy* (Aggiungi tenancy) e selezionare il tenant e il ruolo dell'utente in tale tenancy nei nuovi campi di immissione.
. Per rimuovere l'accesso dell'utente a un tenancy, individuare il tenancy nell'elenco tenancy (tenancy) e selezionare l'icona Delete (Elimina).
. Fare clic su *Aggiorna*.

