---
sidebar: sidebar 
permalink: sewebiug_create_an_object_storage_group.html 
keywords: netapp, keystone, create, object, storage, group, 
summary: Keystone crea un gruppo di storage a oggetti 
---
= Creare un gruppo di storage a oggetti
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Utilizzare questo metodo per creare un gruppo di storage a oggetti.

.Fasi
. Visualizzare l'elenco dei gruppi di storage a oggetti da *ARCHIVIAZIONE A OGGETTI > Gestione utenti > gruppi*.
. Assicurarsi di aver selezionato il subtenant corretto e di aver fatto clic sulla scheda *Groups* (gruppi).
. Fare clic su *Create Group* (Crea gruppo).
. Nella finestra di dialogo Crea gruppo, immettere il nome del gruppo.
. Selezionare il criterio S3 dall'elenco. Per informazioni sui criteri S3, vedere https://docs.netapp.com/us-en/storagegrid-116/s3/bucket-and-group-access-policies.html#specify-permissions-in-a-policy["Specificare le autorizzazioni in un criterio"].
. Fare clic su *Create* (Crea). In questo modo viene creato un lavoro per creare il gruppo con le impostazioni specificate.


.Al termine
Crea gruppo di storage a oggetti viene eseguito come processo asincrono. È possibile controllare lo stato del lavoro nell'elenco dei lavori. Per informazioni sul monitoraggio dei processi, vedere link:sewebiug_netapp_service_engine_web_interface_overview.html#jobs-and-job-status-indicator["qui"].
