---
sidebar: sidebar 
permalink: sewebiug_managing_azure_netapp_accounts.html 
keywords: netapp, keystone, managing, azure, accounts, 
summary: Gestione degli account NetApp Azure 
---
= Gestione degli account NetApp Azure
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
Questa sezione descrive come gestire gli account NetApp Azure:


NOTE: La gestione degli account NetApp di Azure richiede l'accesso dell'amministratore del cliente.

In questa sezione:

* Visualizza un elenco di account Azure NetApp
* Aggiungi un account NetApp Azure
* Modificare i dettagli dell'account Azure NetApp
* Eliminare un account NetApp Azure




== Visualizza un elenco di account NetApp Azure

L'elenco Azure NetApp Accounts (account NetApp Azure) visualizza un elenco di tutti gli account NetApp Azure nelle tenancy a cui l'utente connesso ha accesso. Per visualizzare l'elenco, selezionare *AMMINISTRAZIONE > Azure NetApp Accounts* dal menu.

L'elenco visualizza semplici informazioni su ciascun account NetApp Azure. Le icone delle azioni accanto a ciascun account Azure NetApp consentono di modificare o eliminare l'account Azure NetApp.



== Aggiungi un account NetApp Azure

Questa sezione descrive come aggiungere un account NetApp Azure.

.Prima di iniziare
Sono necessari:

* Il subtenant a cui appartiene l'account NetApp Azure
* L'istanza ANF
* La posizione di Azure (regione)
* Azure Resource Group
* Un nome per l'account


.Fasi
. Selezionare *AMMINISTRAZIONE > Azure NetApp Accounts* dal menu.
. Fare clic su *Create* (Crea).
. Nella finestra di dialogo Create Azure NetApp account (Crea account NetApp Azure), specificare il sottotenant, la posizione (regione) di Azure, il gruppo di risorse Azure e un nome per l'account NetApp Azure.
. Se necessario, aggiungere tag all'account.
. Fare clic su *Create* (Crea). Una volta creato correttamente, lo stato dell'account avrà esito positivo (può essere visualizzato nell'elenco degli account NetApp di Azure).




== Modificare i tag degli account Azure NetApp

Utilizzare questo metodo per modificare i tag associati a un account NetApp Azure.

.Fasi
. Selezionare *AMMINISTRAZIONE > Azure NetApp Accounts* dal menu.
. Individuare l'account NetApp Azure nell'elenco e fare clic sull'icona di modifica.
. Nella finestra di dialogo Manage Azure NetApp account, aggiungere, rimuovere o modificare i tag secondo necessità.
. Fare clic su *Aggiorna*.




== Eliminare un account NetApp Azure

Utilizzare questo metodo per eliminare un account NetApp Azure.

.Fasi
. Selezionare *AMMINISTRAZIONE > Azure NetApp Accounts* dal menu.
. Individuare l'account Azure NetApp nell'elenco e fare clic sull'icona di eliminazione.
. Nella finestra di dialogo Conferma eliminazione, immettere il nome dell'account Azure NetApp da eliminare.
. Fare clic su *Conferma*.

